### ISSUE TITLE
edit tags in galaxy.yml

### ISSUE THREAD

**Issue by thedoubl3j** [IBM/ansible-power-aix#10]
The tags currently found in the galaxy.yml file would be good for a blog post but AH utilizes these tags to help users find specific, preset tags based on use case. This list can be found when first landing in AH. 

![Screenshot from 2020-06-02 17-40-27](https://user-images.githubusercontent.com/24478650/83572829-44b86000-a4f8-11ea-982f-af195a07f265.png)

I would add just infrastructure to this list.

**Comment by pbfinley1911** [comment]
Resolved in upcoming commit
