### ISSUE TITLE
AWX - ibm.power_aix.nim_suma - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by SteveMunday62** [IBM/ansible-power-aix#101]
Describe the bug
When running nim_suma against a specific AIX 7.1 node via AWX the nim_suma.py code errors out with 

AttributeError: 'NoneType' object has no attribute 'group'

To Reproduce
Use the following .yml and replace <LPAR-name> with one you have

`---
- name: "Run Service Update Management Assistant (SUMA) on AIX"
  hosts: all 
  gather_facts: true
 
  tasks:
    - name: Check NIM for resources
      ibm.power_aix.nim_suma:
        action: preview
        targets: <LPAR-name>
        oslevel: Latest`

This will then generate the following:

`Identity added: /tmp/bwrap_48_87hq4ee6/awx_48_6o6isp5l/artifacts/48/ssh_key_data (/tmp/bwrap_48_87hq4ee6/awx_48_6o6isp5l/artifacts/48/ssh_key_data)
PLAY [Run Service Update Management Assistant (SUMA) on AIX] *******************
TASK [Gathering Facts] *********************************************************
[WARNING]: Platform aix on host xyz is using the discovered Python
interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen
ce_appendices/interpreter_discovery.html for more information.
ok: [xyz]
TASK [Check NIM for resources] *************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'group'
fatal: [xyz]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n File \"<stdin>\", line 102, in <module>\n File \"<stdin>\", line 94, in _ansiballz_main\n File \"<stdin>\", line 40, in invoke_module\n File \"/opt/freeware/lib/python2.7/runpy.py\", line 188, in run_module\n fname, loader, pkg_name)\n File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\n mod_name, mod_fname, mod_loader, pkg_name)\n File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\n exec code in run_globals\n File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1083, in <module>\n File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_…
PLAY RECAP *********************************************************************xyz : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
`
module_stderr contains the following

`  "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1083, in <module>\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1072, in main\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 879, in suma_download\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 546, in compute_rq_name\nAttributeError: 'NoneType' object has no attribute 'group'\n",
  "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1083, in <module>\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1072, in main\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 879, in suma_download\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_Bex85_/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 546, in compute_rq_name\nAttributeError: 'NoneType' object has no attribute 'group'\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}
`

Expected behavior
Return TL / SP details of target(s).

Screenshots
N/A

Environment (please complete the following information):
 - OS: Host/NIM (AIX 7200-03-02-1845), Node (AIX 7100-05-05-1939)
 - Python Version: 2.7
 - OpenSSH Version: Host/NIM (1.0.2.2100), Node (1.0.2.1801)
 - Ansible Version: 2.9
 - AIX Collection Version: 1.2.1

Additional context
N/A

**Comment by raeyacld** [comment]
You have the follow errors in your playbook:
targets: 
---> it is an unsupported parameter for ibm.power_aix.suma module
oslevel: Latest` 
---> a wrong oslevel format, it should be oslevel: 'latest'

Please correct those errors in your playbook and rerun, update the issue if you still have errors

**Comment by SteveMunday62** [comment]
Thanks for reviewing things.  I was following the Examples in [https://ibm.github.io/ansible-power-aix/modules/suma.html) which has oslevel: Latest rather than oslevel: 'latest'.  In addition, in the Parameter section for oslevel it also states Latest rather than 'latest'.

Revised .yml

`- name: Run "SUMA" tasks against AIX
  hosts: all 
  gather_facts: true

  tasks:
    - name: Check system updates for the current oslevel of the system
      ibm.power_aix.suma:
        action: preview
        oslevel: 'latest'`

Now getting the following:

`{
  "changed": false,
  "stdout": "",
  "cmd": "/usr/sbin/suma -x -a RqType=Latest -a Action=Preview -a DLTarget=/usr/sys/inst.images -a DisplayName=preview request for oslevel latest -a FilterDir=/usr/sys/inst.images -a Extend=y",
  "meta": {
    "messages": [
      "SUMA - Command: /usr/sbin/suma -x -a RqType=Latest -a Action=Preview -a DLTarget=/usr/sys/inst.images -a DisplayName=preview request for oslevel latest -a FilterDir=/usr/sys/inst.images -a Extend=y"
    ]
  },
  "stderr": "****************************************\nPerforming preview download.\n****************************************\n0500-008 An error occurred attempting to get configuration settings.\n0500-041 The following system command failed:\n\tgrep\nThe error was as follows:\n\t\n",
  "invocation": {
    "module_args": {
      "save_task": false,
      "description": null,
      "task_id": null,
      "download_only": false,
      "extend_fs": true,
      "sched_time": null,
      "oslevel": "latest",
      "download_dir": "/usr/sys/inst.images",
      "action": "preview",
      "metadata_dir": "/var/adm/ansible/metadata",
      "last_sp": false
    }
  },
  "msg": "Suma Preview command '/usr/sbin/suma -x -a RqType=Latest -a Action=Preview -a DLTarget=/usr/sys/inst.images -a DisplayName=preview request for oslevel latest -a FilterDir=/usr/sys/inst.images -a Extend=y' failed with return code 1",
  "stdout_lines": [],
  "stderr_lines": [
    "****************************************",
    "Performing preview download.",
    "****************************************",
    "0500-008 An error occurred attempting to get configuration settings.",
    "0500-041 The following system command failed:",
    "\tgrep",
    "The error was as follows:",
    "\t"
  ],
  "_ansible_no_log": false
}`

**Comment by raeyacld** [comment]
I see. A file system for containing the updates from download needs to be created before preview or download. The file system related tasks are included in the demo_suma.yml You might want to try that instead of using the one you created. It is located at ../ansible_collections/ibm/power_aix/playbooks/demo_suma.yml, let me know if you could not find it. Thanks.

**Comment by SteveMunday62** [comment]
Hi, the /usr/sys/inst.images directory already exists on the NIM server so I'm not sure that's the issue here.

I can run the following (pulled from the AWX JSON error log) from the NIM CLI which works fine.

`/usr/sbin/suma -x -a RqType=Latest -a Action=Preview -a DLTarget=/usr/sys/inst.images -a DisplayName="AIX_SUMA_demo" -a FilterDir=/usr/sys/inst.images -a Extend=y`

The SUMA logs have the following, the top piece is the result of the manual execution and the lower piece is from the playbook.

`20210607 10:38:25 I Total bytes of updates downloaded: 10327118336
20210607 10:38:25 I Summary:
20210607 10:38:25 I         1259 downloaded
20210607 10:38:25 I         1 failed
20210607 10:38:25 I         0 skipped
20210607 10:38:25 I Logging operations stopped, Mon Jun  7 10:38:25 2021.
20210607 10:38:53 I Logging operations started, Mon Jun  7 10:38:53 2021.
20210607 10:38:53 W ****************************************
20210607 10:38:53 W Performing preview download.
20210607 10:38:53 W ****************************************
20210607 10:38:54 E 0500-008 An error occurred attempting to get configuration settings.
20210607 10:38:54 E 0500-041 The following system command failed:
        grep
The error was as follows:

20210607 10:38:54 I Logging operations stopped, Mon Jun  7 10:38:54 2021.`

Many thanks, Steve

**Comment by raeyacld** [comment]
I am not able to recreate the issue on my AIX 72 and previous AIX 71 systems, however, I don't have the same AIX71 level as you have.

Did you run the suma command on AIX system local successfully? what is your Java version? thanks

**Comment by SteveMunday62** [comment]
On the NIM we have the following

`amrsomanim3:/# oslevel -s
7200-03-02-1845
amrsomanim3:/# lslpp -l | grep -i java
  Java7_64.jre             7.0.0.625  COMMITTED  Java SDK 64-bit Java Runtime
  Java7_64.sdk             7.0.0.625  COMMITTED  Java SDK 64-bit Development
                             3.2.1.0  COMMITTED  RSCT GUI JAVA Msgs - U.S.
                             3.2.1.0  COMMITTED  RSCT RMC JAVA Msgs - U.S.
  Java7_64.jre             7.0.0.625  COMMITTED  Java SDK 64-bit Java Runtime
amrsomanim3:/#
`
If I run the following on the NIM command line it works

`/usr/sbin/suma -x -a RqType=Latest -a Action=Preview -a DLTarget=/usr/sys/inst.images -a DisplayName="AIX_SUMA_demo" -a FilterDir=/usr/sys/inst.images -a Extend=y`

Here's an excerpt from the log

`amrsomanim3:/# cat /var/adm/ras/suma.log
20181119 13:26:37 I Logging operations started, Mon Nov 19 13:26:37 2018.
20181119 13:26:37 V Creating stanza database /var/suma/data/policy.suma.
20210607 08:53:51 I Logging operations started, Mon Jun  7 08:53:50 2021.
20210607 08:53:51 W ****************************************
20210607 08:53:51 W Performing preview download.
20210607 08:53:51 W ****************************************
20210607 08:54:38 I Download SUCCEEDED: /usr/sys/inst.images/installp/ppc/7200-03-06.bff
20210607 08:54:38 I Download SUCCEEDED: /usr/sys/inst.images/installp/ppc/U888320.bff
20210607 08:54:38 I Download SUCCEEDED: /usr/sys/inst.images/installp/ppc/U888319.bff
20210607 08:54:38 I Download SUCCEEDED: /usr/sys/inst.images/installp/ppc/U887927.bff
. . . . .
20210610 06:12:40 I Download SUCCEEDED: /usr/sys/inst.images/installp/ppc/U881716.bff
20210610 06:12:40 I Download SUCCEEDED: /usr/sys/inst.images/installp/ppc/U881704.bff
20210610 06:12:40 I Total bytes of updates downloaded: 3164157440
20210610 06:12:40 I Summary:
20210610 06:12:40 I         449 downloaded
20210610 06:12:40 I         0 failed
20210610 06:12:40 I         0 skipped
20210610 06:12:40 I Logging operations stopped, Thu Jun 10 06:12:40 2021.
amrsomanim3:/#`

**Comment by raeyacld** [comment]
1. All the suma errors reported are from a same AIX node (7100-05-05-1939), no matter from suma command or ansible suma module run, is this right?  Did you check if this node has /usr/sys/inst.image in place?
2. I am assuming amrsomanim3 is a NIM server, and suma command succeeded on it, are you able to run ansible suma module to verify?

According to the error logs, the error occurred from suma collecting configurations via grep command with exit 13. It could be intermittent problem, network issue. Can you retry on the same AIX node to see if you can recreate the issue? meanwhile, I will see if I can reproduce...

**Comment by SteveMunday62** [comment]
Currently I'm limiting the AIX target node I run the SUMA on.  The node is running AIX 7100-05-05-1939.

If I manually run the SUMA process directly on the target node it works.  If I point the AWX managed process (hosted on amrsomanim3 which is an AIX 7.2 NIM) at the same target node I get the "grep" error.

Many thanks, Steve

**Comment by raeyacld** [comment]
The closest AIX 71 level I can find is 7100-05-05-1937. Still could not reproduce the issue neither from nim_suma module managed by an Ansible control node nor the suma command running on the local. The issue is most likely related to AWX. Can you let me know the following info:
1. What is your AWX version on AIX? 
2. Are you able to run "lsnim" on amrsomanim3? 
3. is your target AIX node (7100-05-05-1939) managed as a standalone machine by amrsomanim3? 
    ( run "lsnim |  grep {target hotname}" to verify)
4. Do you have an Ansible control node?

**Comment by SteveMunday62** [comment]
Hi, I think you've hit upon something.

a) NIM=amrsomanim3 running AIX 7.2
b) AWX running on amrsomanim3 (i.e. the AIX 7.2 NIM)
c) The AIX node (amrasteve1) is running AIX 7.1 and deployed from the NIM running AIX 7.1
d) lsnim on amrsomanim3 doesn't list amrasteve1 as it's managed/deployed by the NIM running AIX 7.1

So, I think I'm trying to do something that isn't do-able, correct?

Many thanks, Steve

**Comment by raeyacld** [comment]
We don't have AWX setting in our lab env. To understand the issue of grep and setting better, could you please reproduce the issue and collect the sume logs. 

1. set TRACE_LEVEL=INFO in /var/suma/data/eccBase.properties
2. collect the following logs
#cd /var/suma/log/
eccAudit0.0.log
eccTrace0.0.log
#cd /var/adm/ras/
suma.log

**Comment by raeyacld** [comment]
Need more info to debug further. We will stop working on this until more logs are provided.
