### ISSUE TITLE
ibm.power_aix.nim should be able to define NIM resources

### ISSUE THREAD

**Issue by stephenulmer** [IBM/ansible-power-aix#109]
**Is your feature request related to a problem? Please describe.**
When setting up or maintaining a NIM server with the power_aix collection, there is no way to define resources from existing files or from other resources.

**Describe the solution you'd like**
I would like to be able to use power_aix.nim to define at least this subset of the NIM object types:
  - lpp_source
  - spot
  - bosinst_data
  - exclude_files
  - mksysb
  - script
  - fb_script
  - res_group (I never used to use these, but it's currently *required* to actually perform an install with power_aix.nim)

I am working around this as described below, but need to begin removing my work-around code as we get closer to production deployments.

**Describe alternatives you've considered**
I'm currently using the **command** module to run *nim -o define*, and burning YAML to make it as idempotent as possible. This method requires the end-user to perform duties in the play that are better implemented inside the module.

**Additional context**
I am happy to implement this, but want an issue tracking it to avoid duplicate effort.

A generic *define* operation will eventually cause a breaking change, as *define_script* should be subsumed by it. The initial implementation can stub *define_script* to the new, internal, generic *define* logic. I will need to be directed on how that deprecation should work.

My initial idea is to add the rest of the object type keys as parallels to lpp_source, script, etc., and use them appropriately for *define* (and eventually *bos_inst* and other operations). I **think** there is always a polarity so that this would be well-defined. For example, one can define a spot from an lpp_source, but not the other way around.

**Comment by pvtorres** [comment]
Stephen, because the issue has been labeled enhancement, we can use this issue to track the effort. So no work will be duplicated. We are open to receive your contribution on allowing the nim module to input the attribute to define a resource. The define can be use as the action as we have a define_script action to distinguish the process of reading the define configuration from the script.

**Comment by stephenulmer** [comment]
Just noting here that I know that this is being worked-on by the IBM team (so nobody puts in work that will be obsoleted).

**Comment by pvtorres** [comment]
Stephen, 
We created the nim_resource module to allow the definition of nim object related to resources. 

https://github.com/IBM/ansible-power-aix/blob/dev-collection/plugins/modules/nim_resource.py




> Example:

        name: Define a NIM lpp_source.  
        ibm.power_aix.nim_resource:
        action: create
        name: lpp_730
        object_type: lpp_resource
        attributes:
             source: /software/AIX7300
             location: /nim1/copy_AIX7300_resource
