### ISSUE TITLE
Reboot module in a playbook does not complete for 2 hours

### ISSUE THREAD

**Issue by fghoraishi** [IBM/ansible-power-aix#113]
When we use the aix reboot module in a playbook, it did the reboot successfully of the target but the playbook does not complete till 2 hours later.

We tried various reboot_timeout values and it did not help.

Faad

---
- name: reboot aix systems
  hosts: aix
#  gather_facts: false
  tasks:
    - name: "Reboot a machine"
      ibm.power_aix.reboot:
        pre_reboot_delay: 30
        post_reboot_delay: 10
        reboot_timeout: 100

**Comment by nitismis** [comment]
This bug seems to be introduced after we provided fix for type error earlier. Working on this as high priority.

**Comment by nitismis** [comment]
I have tried various scenarios to recreate the issue but the module is working fine on our test setup.

**Comment by nitismis** [comment]
I have tried all the scenario in our test environment and I am not able to recreate the issue. The module is working as per expectation. I am closing the issue but please reopen the issue if you encounter same error again with all the logs.
