### ISSUE TITLE
lvg module fails for non Scalable vgs

### ISSUE THREAD

**Issue by 0rphu** [IBM/ansible-power-aix#131]
**Describe the bug**
When modifying a VG, -M switch is presumably implicitly added. This switch is invalid for small or big VG. Extending rootvg fails.

**To Reproduce**
`   - name: Extend rootvg
      ibm.power_aix.lvg:
        vg_name: rootvg
        pvs: hdisk0
        state: present`

**Expected behavior**
VG is extended and returns changed. Currently, rootvg is extended, but the modules subsequently fails.

`FAILED! => {"changed": false, "cmd": "chvg -M n   rootvg ", "msg": "Volume group rootvg extended.\nFailed to modify volume group rootvg attributes. Command 'chvg -M n   rootvg ' failed.", "rc": 2, "stderr": "0516-1616 chvg: This operation is only valid for scalable volume groups.\n0516-732 chvg: Unable to change volume group rootvg.\n", "stderr_lines": ["0516-1616 chvg: This operation is only valid for scalable volume groups.", "0516-732 chvg: Unable to change volume group rootvg."], "stdout": "", "stdout_lines": []}`

**Screenshots**

**Environment (please complete the following information):**
 - OS: AIX 7.2.4.1
 - Python Version: 3.8.2
 - OpenSSH Version: OpenSSH_7.1p1 
 - Ansible Version: 2.10.3
 - AIX Collection Version: 1.2.1

**Additional context**

**Comment by jdejoya17** [comment]
Hi, thank you for bringing this up.

This issue is resolved in latest version of this collection on our github IBM repo.

sample playbook:
```
  tasks:
  - name: "extend rootvg"
    lvg:
      state: present
      vg_name: rootvg
      pvs: hdisk1
    register: results
  - debug: var=results
```

results:
```
TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [x.x.x.x] => {
    "results": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        },
        "changed": true,
        "cmd": "extendvg  rootvg hdisk1",
        "failed": false,
        "msg": "Volume group rootvg extended.\n",
        "rc": 0,
        "stderr": "",
        "stderr_lines": [],
        "stdout": "Physical Volume   Mirror Pool       \nhdisk0            None              \nhdisk1            None              \n",
        "stdout_lines": [
            "Physical Volume   Mirror Pool       ",
            "hdisk0            None              ",
            "hdisk1            None              "
        ],
        "warnings": [
            "Platform aix on host 9.3.141.217 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information."
        ]
    }
}
```

We don't have a new release yet, but you can clone the latest repo
to check out the recent changes.

Thank you for your time.
