### ISSUE TITLE
Remove old_rootvg when using 'clean' in alt_disk module

### ISSUE THREAD

**Issue by roxyland** [IBM/ansible-power-aix#142]
**Is your feature request related to a problem? Please describe.**
Using action 'clean' with alt_disk does not remove old_rootvg.

**Describe the solution you'd like**
When using 'clean' in alt_disk, additional parameters should be made available to remove old_rootvg and free up disks.

**Describe alternatives you've considered**
Tried using a alt_rootvg_op -X old_rootvg instead, but this alone doesn't offer a working solution as a subsequent 'copy' action to re-use the freed up 'old_rootvg' disk still fails because get_free_pvs runs 'lquerypv -V disk' and continues/skips the disk if stdout.strip() != "1"

**Comment by roxyland** [comment]
Adding output from alt_disk.py that prints out debug disk information

 [.ansible/tmp/ansible-tmp-1629765027.5765903-25524-25062912460462]# python AnsiballZ_alt_disk.py execute
List of PVs:
    pvs[hdisk1]: {'status': '', 'pvid': '00f98ff6475da314', 'vg': 'None'}
    pvs[hdisk0]: {'status': 'active', 'pvid': '00f98ff6475da210', 'vg': 'rootvg'}
Matched disk with "None": hdisk1
stdout of lquerypv on hdisk1: 0
Skipping hdisk1 because lquery stdout != 1
List of available PVs:

{"stdout": "", "changed": false, "failed": true, "stderr": "", "invocation": {"module_args": {"first_boot_script": null, "force": false, "device_reset": false, "disk_size_policy": "nearest", "remain_nim_client": false, "bootlist": false, "resolvconf": null, "action": "copy", "targets": null}}, "msg": "No free disk available"}

**Comment by jdejoya17** [comment]
Hello,
The issue regarding the alt_disk copy showing giving the error "No free disk available" was resolved in a previous PR.
This was the issue the PR was for:
https://github.com/IBM/ansible-power-aix/issues/61

You can get the latest version in our github repo.

Thank you
