### ISSUE TITLE
Module for NIM Support: add nim client registration

### ISSUE THREAD

**Issue by surajsub** [IBM/ansible-power-aix#152]
Request a module that will allow aix client to register with NIM . Similar to rh registration.

**Describe the solution you'd like**
1)Customer provisions an aix lpar
2) The ansible playbook should execute code on the nim server to register it with nim .

**Describe alternatives you've considered**
1) Execute a script on the nim server to register the client using standard shell commands.

**Additional context**

**Comment by d-little** [comment]
Would it not be best to register the Client itself with NIM?  Perhaps as an option for either way.

nimclient -l returning success is a good proof that it works.

```shell
{
  MASTER="${NIMMASTER}"
  CLIENTNAME="$(uname -n)"
  IF="en0"
  [[ -e /etc/niminfo ]] && mv /etc/niminfo /etc/niminfo.backup.$(date +%Y%m%d%H%M)
  niminit -aname="${CLIENTNAME}" -amaster="${MASTER}" -apif_name="${IF}"
  nimclient -c    # switch to ssl
  nimclient -l    # make sure there's an output from the master
}
```

**Comment by nitismis** [comment]
We have planned this in our next release.
