### ISSUE TITLE
ibm.power_aix.user with change_passwd_on_login: false gives error on Failed to set password for the user:

### ISSUE THREAD

**Issue by stephannavarro** [IBM/ansible-power-aix#154]
**Describe the bug**

When using ibm.power_aix.user with change_passwd_on_login: false gives error on Failed to set password for the user:....

**To Reproduce**
use this playbook : 
---
- hosts: all
  gather_facts: false
  user: root
  collections:
    - ibm.power_aix

  tasks:
  - name: creating user / changing password
    ibm.power_aix.user:
      state: present
      name: user003
      change_passwd_on_login: false
      password: PWmvGs9zn/.0g
      #password: is root
      attributes:
        home: /home/user002

**Expected behavior**
user to be created without error 

**Screenshots**

**Environment (please complete the following information):**
 - OS: AIX 7200-02-01-1731
 - Python Version: 2.7.
 - AIX Collection Version: 1.2.1

**Additional context**
To fix I edited file /ibm/power_aix/plugins/modules/user.py
on line 281 
 cmd = "echo \'{user}:{password}\' | chpasswd -ec".format(user=name, password=passwd)
changed to 
 cmd = "echo \'{user}:{password}\' | chpasswd -e -c".format(user=name, password=passwd)

**Comment by pvtorres** [comment]
Stephen, were you able to run this playbook and then able to log in with that password? 
Also, are you using an AIX system as the ansible controller or a Linux system?

**Comment by stephannavarro** [comment]
Ola pedro 

Yes I was able to login with the password. 
The ansible engine runs on linux.
