### ISSUE TITLE
how to encypt password in AIX user module

### ISSUE THREAD

**Issue by fghoraishi** [IBM/ansible-power-aix#166]
I am not able to create a user on AIX using Ansible AIX collection's user module that get a valid password.

The user gets created and the /etc/security/passwd shows an encypted password for the user but I cannot log into the user with that password.

Can you you tell me how I should encrypt the password parameter?
I have used all these encryptions and none works.

{{ 'test1'|hash('sha1') }}
To get the md5 hash of a string:
{{ 'test1'|hash('md5') }}
Get a string checksum:
{{ 'test2'|checksum }}
Other hashes (platform dependent):
{{ 'test2'|hash('blowfish') }}
To get a sha512 password hash (random salt):
{{ 'passwordsaresecret'|password_hash('sha512') }}

Thanks
Faad
IBM

**Comment by pvtorres** [comment]
Faad and I had a conversation and the way Faad was able to create the hash was going to an AIX server and creating a password for a dummy user, then extracting the encrypted password from the /etc/security/passwd and then using this hash with the ibm.power_aix.user module. 

AIX default hashing is not compatible with other operating systems. 
But users can download an open source package that will allow AIX to decode hash passwords from other operating systems. 
The current AIX collection does have a filter (such as the password_hash) dedicated to hashing the passwords in the way AIX is expecting it. 
One way to overcome this situation is to download the AIX loadable password algorithm (LPA) from the AIX Web download Packs program and follow some steps for the configuration. 
https://www.ibm.com/support/pages/aix-making-sha-256-and-sha-512-passwords-compatible-other-oss

**Comment by fghoraishi** [comment]
Hi Pedro

Just to add that the hashed password can be found in /etc/security/passwd file.

Faad
