### ISSUE TITLE
Incomplete documentation for user module

### ISSUE THREAD

**Issue by McBschire** [IBM/ansible-power-aix#180]
Moin Team, 

Changing the password of an existing user does not work as documented.
https://ibm.github.io/ansible-power-aix/modules/user.html says:

```
password (optional, str, None)

    Specifies the encrypted string for the password to create or change the password.

    Can be used when state=present.
```

IMHO it shoud be 

```
password (optional, str, None)

    Specifies the encrypted string for the password to create or change the password.

    Can be used when state=present or state=modify.
```

as state=present do not change the password, if the user already exists.

With state=modified it is working.

Hopefully you would like to get this kind of issues. 

With kind regards from Hamburg/Germany
Oliver

**Comment by pvtorres** [comment]
Thank  you Oliver.

**Comment by Gabriel-Canton** [comment]
Hi Pedro, congratulations for the great work! I was confused by the same statement Oliver mentions... Furthermore, if you happen to change it, I was also very confused by the part thats says "Specifies the _encrypted_ string for the password to create or change the password.". At first I thought the use of "encrypted" was a mistake, and spent a lot of time trying to figure out why the change seemed to work but I wasn't able to log in using the password I had supplied. I needed to look at the code and see you were using chpasswd -e to understand what was going on. Then I had to spend some more time trying to find out how to produce a valid hashed password... 

I'm sure others will get it faster than me, but if I may make a suggestion, to make it easier to use the module, it could be helpful to comment a little about this. For example, you could tell "Specifies the encrypted string for the password to be input to the chpass -e command. This can be generated using the ansible.builtin.password lookup, or the ansible.builtin.command module to run the openssl passwd -crypt command, depending on the password hashing algorithm (defined by the pwd_algorithm attribute in /etc/security/login.cfg) used by the target host."

Thanks and regards,

Gabriel

**Comment by pvtorres** [comment]
@Gabriel-Canton , excellent suggestion. 
The problem that is facing that command is related to the encrypted algorithm AIX uses vs Linux or other operating systems. AIX by default is not compatible with SHA 256 or SHA 512 passwords in the way Linux encrypt them. 
Like you explained, the user can  encrypt the password in AIX using "openssl passwd -crypt <password>  " and use that encrypted password in the user module password attribute. 

The other way to do it is configuring AIX to encrypt/decrypt Linux encryption style passwords.

This is done by downloading and installing the loadable pwmod and then adding some lines in the /etc/security/pwdalg.cfg" to tell AIX how to decode the passwords.  Once this is installed/configured, the user can pass encrypted passwords

This is explained in more details in the next link:
https://www.ibm.com/support/pages/aix-making-sha-256-and-sha-512-passwords-compatible-other-oss

Once AIX is configured to handle this SHA256 and SHA512 Linux style passwords, 
The only thing that needs to be done is to encrypt the password from the playbook

password: "{{ clear_text_password |  password_hash('sha256') }} "

There are some licensing issues with the pwmod module that prevent us to package it in a role to automate this configuration.
