### ISSUE TITLE
Problem using nim_suma module. AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Jbarboza06** [IBM/ansible-power-aix#182]
Hello,

I tried to use the nim_suma module for download and create an lpp_source but I facing the next error: 

"module_stdout": "Traceback (most recent call last):\r\n  File \"/home/svc_ansible_twr/.ansible/tmp/ansible-tmp-1639496919.577661-9-251273278428090/AnsiballZ_nim_suma.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/svc_ansible_twr/.ansible/tmp/ansible-tmp-1639496919.577661-9-251273278428090/AnsiballZ_nim_suma.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/svc_ansible_twr/.ansible/tmp/ansible-tmp-1639496919.577661-9-251273278428090/AnsiballZ_nim_suma.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.nim_suma', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/opt/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/opt/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/opt/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_nim_suma_payload_pr4s01eg/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1083, in <module>\r\n  File \"/tmp/ansible_nim_suma_payload_pr4s01eg/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1072, in main\r\n  File \"/tmp/ansible_nim_suma_payload_pr4s01eg/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 884, in suma_download\r\n  File \"/tmp/ansible_nim_suma_payload_pr4s01eg/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 673, in compute_filter_ml\r\nAttributeError: 'NoneType' object has no attribute 'group'\r\n",
    "module_stderr": "Shared connection to rsdcanim01.rimac.com.pe closed.\r\n",

My playbook is: 

- name: AIX Patching Playbook 
  hosts:  nim_master
  gather_facts: False
  become: True
  become_user: root
  vars: 
    oslevel: 7200-05-02
    nim_lpp_source: 7200-05-02-2114-lpp_source
  collections:
    - ibm.power_aix
  tasks:

  - name: CREAR Updates con los últimos parches de AIX 
    nim_suma:
      action: download
      download_dir: "/export/lpp_source"
      lpp_source_name: "{{ nim_lpp_source }}"
      oslevel: "{{ oslevel }}"
      targets: demo_target

I hope you can help me. Thanks in advance.

**Comment by SteveMunday62** [comment]
I also have the exact same issue, hope you can help, many thanks.

AIX collection: v1.4.0

ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.9 (default, Sep 14 2020, 06:09:55) [GCC 8.3.0]

**Playbook**
    - name: Check system updates for the current oslevel of the system
      ibm.power_aix.nim_suma:
        description: AIX_SUMA_demo
        action: preview
        oslevel: 'latest'
        targets: <LPAR-name>
        download_dir: /usr/sys/inst.images
      register: output

`{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1083, in <module>\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1072, in main\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 879, in suma_download\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 546, in compute_rq_name\nAttributeError: 'NoneType' object has no attribute 'group'\n",
  "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1083, in <module>\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1072, in main\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 879, in suma_download\n  File \"/tmp/ansible_ibm.power_aix.nim_suma_payload_AzmzUe/ansible_ibm.power_aix.nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 546, in compute_rq_name\nAttributeError: 'NoneType' object has no attribute 'group'\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}`

**Comment by Jbarboza06** [comment]
> 

Hello Steve, did you find any solution?

**Comment by pvtorres** [comment]
@SteveMunday62  I tried your playbook in 1.4.0 and it requires at least one system for the targets.

**Comment by pvtorres** [comment]
@Jbarboza06, using the release 1.4.0 and your playbook, I am able to download the ptfs for the target node for that particular release. 
 nim server level: 7200-05-03, target node level: 7200-05-01

**Comment by Jbarboza06** [comment]
Hi @pvtorres thanks for your reply. I had to put some debug on the python of nim_suma.py to find the problem. In my case the problem is in te execution of the comand: 

        cmd = ['/usr/lpp/bos.sysmgt/nim/methods/c_rsh',
               machine,
               '"/usr/bin/oslevel -s; echo rc=$?"']

This command fails and all the exectuion of the module and playbook fails. I oppened a case with IBM support.

**Comment by pvtorres** [comment]
@Jbarboza06 Were you able to discover what was the problem? Did you register the client to the server? 
The c_rsh command will run from nim to the client only if the client has been registered to the nim client.

**Comment by pvtorres** [comment]
@Jbarboza06 and @SteveMunday62 , can you please confirm that you are still having the problems with the latest release 1.5.0? 
It seems from @Jbarboza06 debug code, that the problem was the module trying to run the oslevel on the target node. 
The question was if the client was registered to the nim server (can be tested by running the command manually from the nim server:
/usr/lpp/bos.sysmgt/nim/methods/c_rsh <nim_client_hostname> /usr/bin/hostname

**Comment by nitismis** [comment]
This issue is tracked through issue #275 .
