### ISSUE TITLE
Problem in ibm.power_aix.user module when creating a user with a UID

### ISSUE THREAD

**Issue by bofhryan** [IBM/ansible-power-aix#184]
When using the ibm.power_aix.user module to create a user and specifying the uid in the attributes for the user an error is generated that the account exists (error text as follows):
fatal: [target]: FAILED! => {"changed": false, "msg": "\nFailed to modify attributes for the user: user", "rc": 17, "stderr": "Error changing \"id\" to \"1000025\" : Account exists.\n", "stderr_lines": ["Error changing \"id\" to \"1000025\" : Account exists."], "stdout": "", "stdout_lines": []}

**Comment by pvtorres** [comment]
Can you please post the playbook or just the task?
Can you also please specify the collection Release version you are using? current one is 1.4.0

**Comment by bofhryan** [comment]
The issue only arises if you issue the create user specifying a password and the uid (playbook below):
- hosts: test1
  gather_subset: min

  tasks:
          - name: create user
            ibm.power_aix.user:
              name: 'ryans'
              state: present
              password: 'testpassword'
              attributes:
                id: '1000025'
                pgrp: 'staff'
                groups: 'staff'
                gecos: 'Test user'
                maxexpired: '-1'
                maxage: '0'
                admin: 'true'
                rlogin: 'true'
                login: 'true'

**Comment by bofhryan** [comment]
collection release is 1.4.0

**Comment by pvtorres** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/81318963/149208976-a7f9a6d4-7fc3-4681-8f43-0f6232cf1999.png">
I try to reproduce the problem, but it worked. Even for idempotency issues, I ran the command again, and this time it did not try to create the user but it returned with no failures. 

Now, if I try to create a new different user, but the ID is the same (1000025) it will fail with the error you are showing. 

Can you please verify that there is not another user with the same ID? ( lsuser -a id ALL)

**Comment by bofhryan** [comment]
I have verified that there is no other user with the same ID:
ioco_test1:/# lsuser ALL | grep 1000025
ioco_test1:/#

It also does not matter what I make the ID the same error occurs. The user gets partially created with the correct uid but there is no password entry created in /etc/security/passwd.

this is what the user looks like after the ansible job failes:
ioco_test1:/etc/security# lsuser ryans
ryans id=1000025 pgrp=staff groups=staff home=/main/nedcor/home/ryans shell=/usr/bin/ksh gecos=Test user login=true su=true rlogin=true daemon=true admin=true sugroups=ALL admgroups= tpath=nosak ttys=ALL expires=0 auth1=SYSTEM auth2=NONE umask=27 registry=files SYSTEM=compat logintimes= loginretries=3 pwdwarntime=5 account_locked=false minage=0 maxage=0 maxexpired=-1 minalpha=3 minloweralpha=1 minupperalpha=1 minother=1 mindigit=0 minspecialchar=0 mindiff=3 maxrepeats=3 minlen=12 histexpire=26 histsize=24 pwdchecks= dictionlist=/etc/security/passwd.dict core_compress=on core_path=on core_pathname=/corefiles core_naming=on default_roles= fsize=-1 cpu=-1 data=2097152 stack=65536 core=2097151 rss=2097152 nofiles=2000 data_hard=33554432 rss_hard=33554432 roles=
ioco_test1:/etc/security#

/etc/security/user stanza:
ryans:
        admin = true
        rlogin = true
        maxage = 0
        login = true
        maxexpired = -1

I have tried the user creation with many different user names, uid's and and many different systems. All with the same result.

**Comment by bofhryan** [comment]
I have downloaded the latest dev release and the issue no longer exists.

**Comment by pvtorres** [comment]
I will then close the issue. Thanks.
