### ISSUE TITLE
Reboot AIX - Take too long and doing many times

### ISSUE THREAD

**Issue by dfmateus** [IBM/ansible-power-aix#191]
**Describe the bug**
sometimes when reboot AIX servers using a code below, it takes too long to back as evidence system reboot so many times.

**To Reproduce**
`- name: "Executing reboot integrate all patches into the system, Please wait..."`
     `become: true`
       `reboot:`
           `msg: "Reboot initiated by Ansible to fully integrate all patches into the system"`
             `pre_reboot_delay: 20   # Seconds to wait before reboot.`
              `post_reboot_delay: 20  # Seconds to wait for validation after reboot command was successful`
               `connect_timeout: 10`
                `reboot_timeout: 300    # Maximum seconds to wait for machine to reboot and respond to a test command.`
                 `test_command: uptime   # Command to run on the rebooted host to validate system running status.`

I'm already changed some info in **ansible.cfg**
`[ssh_connection]`
`# This is for ibm.power_aix.reboot to avoid ssh hangs`
`ssh_args = -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10`

`[persistent_connection ]`
`command_timeout = 120`

**Expected behavior**
Reboot normally without delay and without multiple times.

**Screenshots**
see the evidence when servers is back after couple of time and run the **last** command.
`reboot    ~                                   Feb 04 20:49 `
`shutdown  pts/1                               Feb 04 20:48 `
`reboot    ~                                   Feb 04 20:47 `
`shutdown  pts/1                               Feb 04 20:45 `
`reboot    ~                                   Feb 04 20:44 `
`shutdown  pts/0                               Feb 04 20:42 `
`ansible   pts/0                  Feb 04 20:42 - System is halted by system administrator.   (00:00)`
`reboot    ~                                   Feb 04 20:41 `

**Environment (please complete the following information):**
 - OS: [e.g. AIX 7200-05-03-2148]
 - Python Version: [3.7.4]
 - OpenSSH Version: [8.1.102.2104]
 - Ansible Version: [2.9]
 - AIX Collection Version: [1.4.0]

**Additional context**

**Comment by dfmateus** [comment]
Hi Team, I saw the module [demo_reboot.yml](https://github.com/IBM/ansible-power-aix/blob/dev-collection/playbooks/demo_reboot.yml) was updated any fix has been done ?

**Comment by cheekm** [comment]
Hi, I've been trying unsuccessfully to get this module to consistently reboot an AIX LPAR just once. I've played with the delay parameters but cannot seem to make any difference. Most times, my LPAR reboots four times.

While it is rebooting, I can see this process for each LPAR:

root      87975  84921  0 14:00 pts/9    00:00:00 ssh -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e1f860806f -tt lab01.lab.upmc.edu /bin/sh -c '/usr/sbin/shutdown -Fr && sleep 0'

**Comment by nitismis** [comment]
There is some issue with openSSH on AIX. It is not keeping track of old connection, so, after reboot, controller node is not able to resume the connection. Which results in controller node waiting for connection infinitely and fails after timeout because it is not able to run the test command.
We are providing a work around in demo_reboot_workaround.yml because we dont know how much time it will take to resolve openSSH in AIX itself.
Thanks

**Comment by xtyudl** [comment]
Hi Nitismis,
Have this issue resolved? I have the same issue, after reboot, the task can not continue, hang for so long time, appreciate if you can help on this issue 
<img width="333" alt="Screenshot 2024-05-29 100840" src="https://github.com/IBM/ansible-power-aix/assets/67250063/18d3c6ce-ed6e-4fd3-bf14-0d271265910e">
```
 - name: Reboot server
      ibm.power_aix.reboot:
        reboot_timeout: 360
      become: true

    - name: Check if all the systems responding to ssh
      local_action:
        module: wait_for
          host={{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}
          port=22
          search_regex=OpenSSH
          delay=15
          timeout=300
          state=started
      ignore_errors: yes
      become: false
```
