### ISSUE TITLE
ibm.power_aix.user module add user with attributes problem

### ISSUE THREAD

**Issue by sandori01** [IBM/ansible-power-aix#192]
The module when used to create a user with attributes incorrectly performs this as a two-step process. 
Whe I try to create a user with a certain user ID this is what I use:
- name: Add User
  ibm.power_aix.user:
          state: present
          name: testuser
          change_passwd_on_login: True
          password: testpassword
          attributes:
                  home: /home/testuser
                  id: 11000

When executing this task, the user gets created with the given id, but the task fails with this:
testhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "msg": "\nFailed to modify attributes for the user: testuser", 
    "rc": 17, 
    "stderr": "3004-692 Error changing \"id\" to \"11000\" : Account exists.\n", 
    "stderr_lines": [
        "3004-692 Error changing \"id\" to \"11000\" : Account exists."
    ], 
    "stdout": "", 
    "stdout_lines": []
}

This results in the rest of the playbook not being executed.  Clearly the module first creates the user and then it tries to change the attributes which of course does not work.

OS: AIX 7200-05-03-2148 (it is the same with our 7.1 machines)
Python: 2.7.13
Ansible 2.9.27
ibm.power_aix collection version: 1.3.1

**Comment by pvtorres** [comment]
Can you please update to the 1.4.0 Collection? Several problems with the user module were fixed on that update.

**Comment by sandori01** [comment]
Thanks, I'll do that.

**Comment by pvtorres** [comment]
@sandori01 I will close the issue. If you see any problem with the 1.4.0, please re-open the issue.
