### ISSUE TITLE
Enhance alt-disk "clean" parameter to remove old_rootvg

### ISSUE THREAD

**Issue by cheekm** [IBM/ansible-power-aix#195]
As of 1.4.0, the alt-disk clean parameter only removes any existing "altinst_rootvg" disk. It would be helpful to permit the removal of old_rootvg disks as well.

**Describe the solution you'd like**
I use the alt-disk module to create a new alt-disk-copy prior to updating AIX. Before doing a "copy", I do a "clean" to remove any existing copy. In most cases, the existing copy is "altinst_rootvg". However, occasionally, the existing copy is "old_rootvg" if the previous update was backed out.

I would like the "clean" parameter to remove both "altinst_rootvg" -or- "old_rootvg".

**Describe alternatives you've considered**
Currently, I have to manually remove any "old_rootvg" copies.

**Additional context**
N/A

**Comment by pvtorres** [comment]
I will discuss this with the development team.

**Comment by nitismis** [comment]
Just use parameter allow_old_rootvg=True, and the module will remove old_rootvg as well.
