### ISSUE TITLE
Is there any plan to create a module to use install_all_updates ? 

### ISSUE THREAD

**Issue by dfmateus** [IBM/ansible-power-aix#203]
**Describe the solution you'd like**
A module to use **install_all_updates** for performing updates in filesets, we're already had a module to [installp – Installs and updates software](https://ibm.github.io/ansible-power-aix/modules/installp.html)

- [install_all_updates](https://www.ibm.com/docs/en/aix/7.2?topic=i-install-all-updates-command)

**Additional context**
Currently I'm using the **shell** module against to updates installed software to the latest level on media and verifies the current recommended maintenance or technology level.

**Comment by pvtorres** [comment]
Have you tried to use the suma/nim_suma modules in this context?

**Comment by nitismis** [comment]
I believe suma/nim-suma covers all the aspects of updates.
