### ISSUE TITLE
How to undo power_aix_bootstrap role?

### ISSUE THREAD

**Issue by nigeldao007** [IBM/ansible-power-aix#208]
Hi,

I successfully ran a playbook with power_aix_bootstrap role.

If I want to cleanly undo this role, is this supported?  If so, how?

Thank you

**Comment by pvtorres** [comment]
There is not an auto-undo for the bootstrap. 
But the bootstrap basically installs the AIX Toosbox for open software. 
These are packages, if you used it for AIX 7.1 or AIX 7.2, to install yum and then, using yum to install python2, dependencies, pycurl and wget (these two used by the vios nim modules and the flrtvc modules from the collection.

You can uninstall manually using the rpm -e <rpm name> --nodeps

To list the rpms installed, you can run:
rpm -q -a | egrep "python|wget|curl|pycurl|pip|yum|dnf"

**Comment by nigeldao007** [comment]
Thank you

On Jul 7, 2022, at 11:29 PM, Pedro V Torres ***@***.***> wrote:

﻿
There is not an auto-undo for the bootstrap.
But the bootstrap basically installs the AIX Toosbox for open software.
These are packages, if you used it for AIX 7.1 or AIX 7.2, to install yum and then, using yum to install python2, dependencies, pycurl and wget (these two used by the vios nim modules and the flrtvc modules from the collection.

You can uninstall manually using the rpm -e --nodeps

To list the rpms installed, you can run:
rpm -q -a | egrep "python|wget|curl|pycurl|pip|yum|dnf"
