### ISSUE TITLE
filesystem module ignores attributes parameter for NFS filesystems

### ISSUE THREAD

**Issue by athomasLRS** [IBM/ansible-power-aix#226]
**Describe the bug**
Creating or modifying an NFS filesystem using the filesystem module doesn't seem to use the attributes parameter

**To Reproduce**
Step 1
Run the task below to create a NFS filesystem
```
    - name: Create NFS filesystem
      ibm.power_aix.filesystem:
        filesystem: '/software'
        state: present
        nfs_server: 'nas'
        device: '/software'
        fs_type: 'nfs'
        attributes: options=soft
        auto_mount: no

```
Output
```
changed: [aixlab03] => {
    "changed": true,
    "cmd": "mknfsmnt -f '/software' -d /software  -h 'nas' -a -t rw -w bg ",
    "invocation": {
        "module_args": {
            "account_subsystem": null,
            "attributes": [
                "options=soft"
            ],
            "auto_mount": false,
            "device": "/software",
            "filesystem": "/software",
            "fs_type": "nfs",
            "mount_group": null,
            "nfs_server": "nas",
            "permissions": null,
            "rm_mount_point": false,
            "state": "present",
            "vg": null
        }
    },
    "msg": "Creation of NFS filesystem '/software' succeeded",
    "rc": 0,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []
}
```
Step 2
View NFS filesystem definition in /etc/filesystems. Notice that "soft" mount option is not present
```
# cat /etc/filesystems
/software:
        dev             = "/software"
        vfs             = nfs
        nodename        = nas
        mount           = false
        options         = bg,intr
        account         = false
```
Step 3
Run the play a 2nd time.  Output
```
ok: [aixlab03] => {
    "changed": false,
    "cmd": "chnfsmnt -a  -f /software -d /software -h nas",
    "invocation": {
        "module_args": {
            "account_subsystem": null,
            "attributes": [
                "options=soft"
            ],
            "auto_mount": false,
            "device": "/software",
            "filesystem": "/software",
            "fs_type": "nfs",
            "mount_group": null,
            "nfs_server": "nas",
            "permissions": null,
            "rm_mount_point": false,
            "state": "present",
            "vg": null
        }
    },
    "msg": "No changes needed in /software",
    "rc": 0,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []
}
```

Step 4
Viewing stanza in /etc/filesystems, now "hard" & "rw" mount options have been added, but they were not specified in the task
```
# cat /etc/filesystems
/software:
        dev             = "/software"
        vfs             = nfs
        nodename        = nas.itsol.local
        mount           = false
        options         = rw,bg,hard,intr
        account         = false

```

**Expected behavior**
stanza in /etc/filesystems should have correct options set

**Environment (please complete the following information):**
 - OS: Tested against AIX 7300-00-02-2220 & AIX 7200-05-04-2220
 - Python Version: Tested against AIX Python 2.7.18 & Python 3.7.12.  Ansible control node has Python version = 3.10.4
 - OpenSSH Version: 8.1.102.2105
 - Ansible Version: ansible [core 2.13.3]
 - AIX Collection Version: 1.5.0

**Additional context**
Also tried attributes: -S in an attempt to add the soft mount option to the mknfsmnt command that gets run.

**Comment by nitismis** [comment]
Issue is assigned to a developer. Working on it !

**Comment by schamola** [comment]
"attributes" is not supported with NFS Filesystem. It is supported only for local filesystem as documented in the module, more information can be found in the AIX documentation : https://www.ibm.com/docs/en/aix/7.2?topic=m-mknfsmnt-command
Right now there is only support for auto_mount, permissions and mount_group in case of NFS.

**Comment by nitismis** [comment]
The fix has been merged. Closing the issue.
