### ISSUE TITLE
What domains must be allowed in Proxy?

### ISSUE THREAD

**Issue by Hiroshi-Suzuki-kyndryl** [IBM/ansible-power-aix#227]
**Describe the bug**
I am trying to deploy ibm.power_aix using ansible-galaxy command in a proxy environment.

The domains allowed by Proxy are as follows:
  galaxy.ansible.com
  ansible-galaxy.s3.amazon.com

An error occurs after the install command is executed.

  command:
    ansible-galaxy collection install ibm.power_aix:1.4.1
  error:
    ERROR! Unknoen error when attemption call Galaxy at 'https://galaxy.ansible.com/aip/': <urlopen error Tunnel connection failed: 502 Bad Gateway>

Are there any other domains that require permission?

**To Reproduce**

**Expected behavior**
The command terminate normally.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Redhat Enterprise Linux 8.4
 - Python Version: 3.6.8
 - OpenSSH Version: 1.1.1g-15
 - Ansible Version: 2.9.27-1
 - AIX Collection Version: 1.4.1

**Additional context**

**Comment by nitismis** [comment]
We have never been able to recreate this issue.  galaxy.ansible.com should work fine. This seems to be an issue with network environment. Because galaxy is an open source community and is reachable.
