### ISSUE TITLE
Add quorum option to lvg

### ISSUE THREAD

**Issue by AIXperts** [IBM/ansible-power-aix#231]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to enable/disable quorum on volume groups.

**Describe the solution you'd like**
A 'quorum: {on|off}' option to lvg.

**Describe alternatives you've considered**
Using 'command' seems to be the only alternative.

**Additional context**

**Comment by AIXperts** [comment]
I am not really sure the process described in your guides work, so I will just start working on this unless someone has any objections.

**Comment by nitismis** [comment]
Hi ! @AIXperts , so have you started working on this.Please let us know your development plan and documentation here.
You can work independently but I am also assigning this to one of our team developers to have sync.

**Comment by AIXperts** [comment]
Hi nitismis,

I have submitted a pull request for this. Hoping I have done it right, have not used GitHub before.

Is this documented elsewhere? If so, I have not come across it.

Regards,
Henrik Morsing

**Comment by AIXperts** [comment]
Hi,

I don't know if I'm reading the messages right, but it looks like it has been blocked again.

git log says it was signed off 6 days ago:

commit 1a997c334611f3788714639e3b037b9b03100b77
Author: Henrik Morsing <henrik@morsing.cc>
Date:   Tue Oct 11 14:16:12 2022 +0100

    Feature: Add quorum to lvg change_vg

    Signed-off-by: Henrik Morsing <henrik@morsing.cc>

so can't see any problem with this.

Have you considered using something other than Git(Hub) for this, as this is the worst bit of rubbish I have had to work with in decades.

Regards,
Henrik Morsing

**Comment by nitismis** [comment]
Hi @AIXperts 
Yes, this signed-off thing is newly introduced by the git community. It's now it our hand, and sometimes it feels irritating but you will get used to it, hopefully :)
Anyways, I see our team has given some review on your PR and requested some change. Once done, we can approve and merge it in the repository.

**Comment by nitismis** [comment]
Closing this issue as PR has been merged.
