### ISSUE TITLE
Issue with URL for flrtvc.py

### ISSUE THREAD

**Issue by smurphyit** [IBM/ansible-power-aix#240]
When running a flrtvc playbook, it fails with errors on wrong location to download the flrtvc_latest.zip file.  The exact error is:
"meta": {"messages": ["Cannot download https://www-304.ibm.com/webapp/set2/sas/f/flrt3/FLRTVC-latest.zip"]}, "msg": "Failed to download FLRTVC-latest.zip"}

If the following is changed from the ibm/power_aix collections directory seems to work:
sed -i 's|https://www-304.ibm.com/webapp/set2|https://esupport.ibm.com/customercare|' plugins/modules/flrtvc.py

However, not something I could change on ansible tower (no access to directory), so this would have to be pushed out as a collection version update.

**Comment by smurphyit** [comment]
This would most likely need to be updated in plugins/modules/nim_flrtvc.py as well.

**Comment by nitismis** [comment]
Both files are fixed. Thanks for reporting !
