### ISSUE TITLE
inittab modules calls mkitab incorrectly

### ISSUE THREAD

**Issue by AIXperts** [IBM/ansible-power-aix#241]
**Describe the bug**
mkitab: 0481-203 Cannot specify more than one parameter.

**To Reproduce**
 - name: Add service to inittab
    when: ansible_os_family == "AIX"  
    ibm.power_aix.inittab:
      name: service
      runlevel: "2"
      action: once
      command: "/home/service/agent start >/dev/console 2>&1"
      insertafter: ctrmc
      state: present
    become: yes

fails with:

fatal: [server]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"action": "once",
"command": "/home/service/agent start >/dev/console 2>&1",
"insertafter": "ctrmc",
"name": "service",
"runlevel": "2",
"state": "present"
}
},
"msg": "\\nFailed to create entry in inittab file: service",
"rc": 1,
"stderr": "mkitab: 0481-203 Cannot specify more than one parameter.\\nUsage:\\tmkitab [-i ident] \\"ident:runlevel:action:command\\"\\n",
"stderr_lines": [
"mkitab: 0481-203 Cannot specify more than one parameter.",
"Usage:\\tmkitab [-i ident] \\"ident:runlevel:action:command\\""
],
"stdout": "",
"stdout_lines": []

**Expected behavior**
Add entry to inittab.

**Screenshots**
See above.

**Environment (please complete the following information):**
 AIX 7.2.4.2
 Python 3.8.0
 OpenSSH_8.1p1, OpenSSL 1.0.2u  20 Dec 2019

 ansible 2.9.26
   config file = /etc/ansible/ansible.cfg
   configured module search path = ['/home/mrsadm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   ansible python module location = /usr/lib/python3.6/site-packages/ansible
   executable location = /usr/bin/ansible
   python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

 "collection_info": {
  "namespace": "ibm",
  "name": "power_aix",
  "version": "1.4.0",
  "authors": [
   "Paul B. Finley (@pbfinley1911)"

**Additional context**
I have looked at the code, and it looks correct, so maybe someone can enlighten me.

**Comment by nitismis** [comment]
Hi @AIXperts 
Give us sometime, we will look into this.

**Comment by nitismis** [comment]
We believe this is the way AIX functions. Code is fine. We are not the right team to answer this question about underlying reason for this behaviour.

Thanks and Regards,
Nitish K Mishra

**Comment by AIXperts** [comment]
Hi Nitismis,

Your answer makes no sense. So you are saying AIX is designed to be broken? The same command Ansible tries to run, works fine if I run it manually.

Can you please post what you ran and the test output?

Regards,
Henrik Morsing
