### ISSUE TITLE
power_aix_bootstrap role needs to change YUM to DNF for AIX 7.3

### ISSUE THREAD

**Issue by sangameshs** [IBM/ansible-power-aix#258]
Opening this issue on behalf of an AIX toolbox user who reported this issue in AIX open source forum.

https://community.ibm.com/community/user/power/discussion/power-aix-bootstrap-role-issue-in-aix-73?ReturnUrl=%2fcommunity%2fuser%2fpower%2fcommunities%2fcommunity-home%2fdigestviewer%3fcommunitykey%3d10c1d831-47ee-4d92-a138-b03f7896f7c9&reply-inline=566b9ef6-f2f4-4bd0-8e67-3820d39acafe

If user has an  ansible playbook as 

---

- name: Prep AIX for Ansible 
  hosts: all
  vars: 
    pkgtype: yum 
  collections:
    - ibm.power_aix
  roles:
    - power_aix_bootstrap​

And then runs it on AIX 7.3 it may file with below error.

fatal: [xx.xx.xxx.xxx]: FAILED! => {"changed": false, "msg": "End playbook for xx.xx.xxx.xxx. Bootstrap yum for AIX version 73 is not supported."}

As YUM is not supported for AIX 7.3 we need to use DNF  while running ansible playbook on AIX 7.3.

But we need to confirm if power_aix_bootstrap role for AIX 7.3 has already included DNF for AIX 7.3

**Comment by nitismis** [comment]
This has been fixed in the latest release.
