### ISSUE TITLE
Allow new NIM client to be defined

### ISSUE THREAD

**Issue by StuC-F88** [IBM/ansible-power-aix#259]
**Is your feature request related to a problem? Please describe.**
Currently the nim_resource module allows you to create resources such as lpp_source, spot and res_group. It doesn't allow you to create a standalone client.

**Describe the solution you'd like**
An option in nim_resouce, to create a standalone client VM. 

**Describe alternatives you've considered**
This is the best module to contain this request

**Additional context**
Currently the nim_resource modules includes the check to see what type of resource you are creating:
....
   if object_type:
        if object_type == "res_group":
            cmd = nim_cmd + ' -o define '
        else:
            cmd = nim_cmd + ' -a server=master -o define '
        cmd += ' -t ' + object_type 
...

As the type is 'standalone' it adds the '-a server=master' to the define command, which fails for a standalone client.

_demo-nim:root:/ > /usr/sbin/nim -a server=master -o define  -t standalone -a if1="NIM_117_Net sc-nim-1 0"  sc-nim-1
0042-001 nim: processing error encountered on "master":
   0042-130 m_mkmac: "server" cannot be specified as an attribute
        for this operation

        ** Use lsnim -q <operation> <object name> or
           lsnim -q <operation> -t <type> to list required and optional
           resources and attributes for a particular NIM operation._

If you remove the '-a server=master' it should work for the standalone client.

_demo-nim:root:/ > /usr/sbin/nim -o define  -t standalone -a if1="NIM_117_Net sc-nim-1 0"  sc-nim-1

demo-nim:root:/ > lsnim -t standalone
sc-nim-1                machines       standalone_

**Comment by nitismis** [comment]
Hi @StuC-F88 !
We will look into the requirement and according to the usability will try to include in the module.

**Comment by paul5gray** [comment]
The server attribute is not applicable to  'vios' or 'cec' resources either.

**Comment by nitismis** [comment]
We have now added the feature in nim module in version 1.7.0
