### ISSUE TITLE
Installing wrong flrt packages

### ISSUE THREAD

**Issue by smurphyit** [IBM/ansible-power-aix#260]
When using the flrt playbook, I had two plays setup.  One will just download the files to the machine using a proxy, and the other installs the downloaded ifixes.  Unfortunately, I have been noticing it is sometimes installing the wrong packages, usually for vios 3.1 instead of the aix counter-part.

For instance, on an AIX 7200-05-04 system, I ran the flrt download and then install playbooks.  It installed the following ifixes:
* IJ40615m4b
* IJ41685s4a
* IJ42379s4a
* IJ44559m4a
* IJ42677s4a
* IJ42163m4a

To get some of the correct ifixes installed, I had to remove 4/6 packages above (leaving the last two).  Then I was able to install the following ifixes manually:
* IJ44425m4a
* IJ43869m4a
* IJ42159s4a
* IJ41974s4a
* IJ43876s4a
* IJ42339s4a
* IJ39876s3a

I can look at setting up a scratch LPAR and trying something like this later in the week.  Is there anything specific I should run to get a debug output which I can provide to help further analyze this issue ?
let me know, thanks.

**Comment by nitismis** [comment]
Hi @smurphyit,
Thanks a lot for reporting the issue, but right now we have very limited resources to work on VIOS collection. It might take sometime for us to fix the issue.

Thanks and Regards,
Nitish

**Comment by smurphyit** [comment]
Good day.  The problem is that the flrt playbook is recognizing some of the
fixes to install as the "vios fix" label incorrectly, instead of the aix
ifix label.

Any vulnerability scanner is scanning for the "aix ifix label", but the
"vios ifix label" was installed instead, as sometimes these labels are
different IDs.

I was looking for a way to correct this so the aix ifix ID is used instead
of the "incorrectly identified ifix ID", which is usually the vios ifix ID.

If there is a way for me to run the flrt playbook in debug mode or
something to help capture the data I can do that.  I would just need to
know the switches etc to run it with.

**Comment by schamola** [comment]
Fixed in #389

**Comment by nitismis** [comment]
PR is merged.
