### ISSUE TITLE
Improved parsing of emgr module output

### ISSUE THREAD

**Issue by SteveMunday62** [IBM/ansible-power-aix#266]
Currently the "emgr" module (action: list) delivers the output from an "emgr -l" command which provides stdout_lines of the following (example):

`    "stdout_lines": [
      "",
      "ID  STATE LABEL      INSTALL TIME      UPDATED BY ABSTRACT",
      "=== ===== ========== ================= ========== ======================================",
      "1    S    IJ44427m2a 02/13/23 11:59:04            IJ44427 POTENTIAL SECURITY ISSUE      ",
      "2    S    IJ45060s1a 02/13/23 11:59:18            IJ45060 POTENTIAL SECURITY ISSUE      ",
      "",
      "STATE codes:",
      " S = STABLE",
      " M = MOUNTED",
      " U = UNMOUNTED",
      " Q = REBOOT REQUIRED",
      " B = BROKEN",
      " I = INSTALLING",
      " R = REMOVING",
      " T = TESTED",
      " P = PATCHED",
      " N = NOT PATCHED",
      " SP = STABLE + PATCHED",
      " SN = STABLE + NOT PATCHED",
      " QP = BOOT IMAGE MODIFIED + PATCHED",
      " QN = BOOT IMAGE MODIFIED + NOT PATCHED",
      " RQ = REMOVING + REBOOT REQUIRED"
    ],`

To make this output useable it would be helpful to have the details split out in a list so that the resultant information can be iterated over for onward processing.

As things stand a "shell: emgr -P | awk '/installp/ { print $3 }'" (or equiv.) plus a "register: <variable>" is needed so that the individual items can be processed.

Many thanks, Steve

**Comment by nitismis** [comment]
Thanks @SteveMunday62, for pitching in with this useful enhancement.

**Comment by schamola** [comment]
Hi @SteveMunday62, I have incorporated the changes.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/113427615/230035194-ca354a9f-59ca-4932-9e42-b0c548033be9.png">

**Comment by SteveMunday62** [comment]
Thank-you very much indeed 👍
