### ISSUE TITLE
alt_disk module should also allow to clean old_rootvg

### ISSUE THREAD

**Issue by syahrul-aiman** [IBM/ansible-power-aix#267]
**Is your feature request related to a problem? Please describe.**
`alt_disk` module only allows to clean `altinst_rootvg`. But cleaning `old_rootvg` is a valid command. Please refer to the following link:
https://www.ibm.com/docs/en/aix/7.1?topic=alt-rootvg-op-command

It specify the following example:
```bash
alt_rootvg_op -X old_rootvg
```

**Describe the solution you'd like**
Line 494 of the `alt_disk` module should also support `old_rootvg`:
https://github.com/IBM/ansible-power-aix/blob/dev-collection/plugins/modules/alt_disk.py#L494

**Describe alternatives you've considered**
run the following shell command manually:
```bash
alt_rootvg_op -X old_rootvg
```

**Additional context**
I'll try to do a PR on this issue.

**Comment by syahrul-aiman** [comment]
Created PR https://github.com/IBM/ansible-power-aix/pull/270

**Comment by nitismis** [comment]
hi @syahrul-aiman ,
I have commented on PR as well. Please post a playbook output for this issue/PR using -vvv option.

**Comment by psyntium** [comment]
Sorry, missed out the comments. Will post it by this week

**Comment by nitismis** [comment]
Have merged the PR, closing this defect.
