### ISSUE TITLE
nim_alt_disk_migration role only works with AIX version of NIM master 

### ISSUE THREAD

**Issue by Rich-J-AIX** [IBM/ansible-power-aix#271]
### **Issues:**
1. nim_alt_disk_migration role only works for NIM master AIX version 

 - The "nim_alt_disk_migration" role will only work if you want to upgrade to the same AIX level as is installed on the NIM master.
 - The nimadm command will work when the NIM Master is at a higher AIX version, but the SPOT must have the "bos.alt_disk_install.rte" package installed at the same version as the NIM Master.

2. Inconsistency in Variable Names

 - Error also exists in "nim_alt_disk_migration/tasks/main.yml" file
 - Uses an undefined variable name "{{ nim_client_v }}" instead of "{{ nim_client }}"

3. Documentation examples shows invalid "control_phases" option

 - Documentation for roll correctly shows **perform_migration** in the "control_phases" options:
    ```
    control_phases:
       validate_nim_resources: true
       perform_migration: false
    ```
 - Whilst the examples incorrectly shows **perform_nim_migration** in the "control_phases" options:
    ```
    control_phases:
        validate_nim_resources: true
        perform_nim_migration: false
    ```
4. alt_disk identification module **nim_select_target_disk.py** only accepts disks with a PVID

5. Role only works when disk names are provided if rootvg is mirrored or uses more than 1 disk
- Only a single target disk is returned by 'nim_select_target_disk.py' 

### **Resolution:**
Created a modified version [https://github.com/Rich-J-AIX/ansible-power-aix](https://github.com/Rich-J-AIX/ansible-power-aix)

Changes: 
1. Allow NIM Master to be a higher version (e.g. AIX v7.3 NIM Master upgrading a client from AIX v7.1 to AIX v7.2)
 - Modified LPP_Source & SPOT checks to allow NIM AIX Version to be higher then Client installation AIX Version
 - Coded  new variable to identify LPP_Source for current NIM Master AIX Version "{{ nim_mast_lpp }}" 
   - "{{ nim_mast_lpp }}" defaults to "{{ lpp_source }}" if not defined
   - Is used for validation checks and to install "bos.alt_disk_install.rte" into the SPOT used by *nimadm*
  ```
  - include_role:
       name: power_aix/nim_alt_disk_migration
    vars:
       nim_client:     "{{ NIM_Client }}"
       target_disk:    "{{ DISK }}"
       lpp_source:     "{{ LPP_Source }}"
       spot:           "{{ SPOT }}"
       nim_mast_lpp:   "{{ NIM_Mast_LPP }}"
  ```
2. Modified "nim_alt_disk_migration/tasks/main.yml" to use "{{ nim_client }}" instead of "{{ nim_client_v }}"

3. Documentation page needs updating to show **perform_migration** instead of **perform_nim_migration**

4. Update **nim_select_target_disk.py** to accepts disks without a PVID
 - Allow disks without PVID to be selected by changing regex search to use:
  ```
  pattern = r"0516-320|0516-1396"
  ```
 instead of
  ```
  pattern = r"0516-320"
  ```

5. Disk names need to be provided if rootvg is mirrored or has multiple disks

**Comment by nitismis** [comment]
Thanks Rich for reporting the issue.
We always knew that, **"nim_alt_disk_migration role only works with AIX version of NIM master"**, is a limitation in our role and we were looking forward to work on this. If you are okay with it .. we can work on this together.

**Comment by Rich-J-AIX** [comment]
Hi Nitish.
Happy to work together on this.
If I make further progess I'll upload my changes to my github fork & if you want anything tested in my environment will be happy to oblige :)

**Comment by nitismis** [comment]
Hi rich we have merged the PR. Closing this defect.
