### ISSUE TITLE
Bootstrap role failed to configure dnf on AIX73 due to dnf_installer.sh issue and playbook execution reported no failed tasks

### ISSUE THREAD

**Issue by Bhargava250** [IBM/ansible-power-aix#274]
**Describe the bug**
We are using the power_aix bootstrap to configure the dnf on AIX 73. The playbook execution reports as successful but it is not installing dnf.

Playbook execution output
====================
TASK [ibm.power_aix.power_aix_bootstrap : Restore dnf bundle to upgrade yum to yum4 if yum is installed.] ***
skipping: [rac2]
skipping: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Restore dnf bundle at the target if yum is not installed.] ***
changed: [rac3]
changed: [rac2]  <<<<<<<<<<<<<<<<<<<<<<<<< **In this step it is trying to configure dnf but it fail to configure on AIX lpar**  <<<<

TASK [ibm.power_aix.power_aix_bootstrap : Check if dnf was installed at /opt/freeware/bin] ***
ok: [rac2] 
ok: [rac3] <<<<<<<<<<<<<<<<<<<< **Also the check dnf is getting pass, I expect the playbook execution fail here** <<<<<<<<

TASK [ibm.power_aix.power_aix_bootstrap : Check if yum link was installed at /opt/freeware/bin] ***
ok: [rac2]
ok: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Update "/usr/bin/python3"] ***********
skipping: [rac2]
skipping: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Unmount target filesystem "/tmp/.ansible.cpdir"] ***
changed: [rac2]
changed: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Remove target filesystem "/tmp/.ansible.cpdir"] ***
changed: [rac3]
changed: [rac2]

TASK [ibm.power_aix.power_aix_bootstrap : Print status] ************************
skipping: [rac2]
skipping: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Print status] ************************
skipping: [rac2]
skipping: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Bootstrap python] ********************
skipping: [rac2]
skipping: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Bootstrap pycurl] ********************
skipping: [rac2]
skipping: [rac3]

TASK [ibm.power_aix.power_aix_bootstrap : Bootstrap wget] **********************
skipping: [rac2]
skipping: [rac3]

PLAY RECAP *********************************************************************
rac2                       : ok=27   changed=6    unreachable=0    failed=0    skipped=23   rescued=0    ignored=0
rac3                       : ok=29   changed=8    unreachable=0    failed=0    skipped=21   rescued=0    ignored=0

With  -vvv option we see rc:1 during execution of shell script dnf_installer.sh
[8:23](https://ibm-systems-power.slack.com/archives/D04DW4A8QNQ/p1677509611175759)
<rac2> SSH: EXEC ssh -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/ansible/.ansible/cp/0dc47c1b79"' -tt rac2 '/bin/sh -c '"'"'/usr/bin/python3 /tmp/.ansible.cpdir/.ansible/tmp/ansible-tmp-1677492176.9868882-2686713-19325219932691/AnsiballZ_command.py && sleep 0'"'"''
<rac3> (1, b'\r\n{"changed": true, "stdout": "Please install openssl 1.0.2.2001 and higher version.\\nYou can download and install latest openssl from AIX web download site\\nhttps://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=aixbp", "stderr": "", "rc": 1, "cmd": ["/tmp/.ansible.cpdir/dnf_installer.sh", "-d", "/tmp/.ansible.cpdir"], "start": "2023-02-27 04:02:59.008558", "end": "2023-02-27 04:02:59.565427", "delta": "0:00:00.556869", "failed": true, "msg": "non-zero return code", "invocation": {"module_args": {"_raw_params": "/tmp/.ansible.cpdir/dnf_installer.sh -d /tmp/.ansible.cpdir", "_uses_shell": false, "warn": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\r\n', b'Connection to rac3 closed.\r\n')
<rac3> Failed to connect to the host via ssh: Connection to rac3 closed.
<rac3> ESTABLISH SSH CONNECTION FOR USER: root
<rac3> SSH: EXEC ssh -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/ansible/.ansible/cp/41958e96c3"' rac3 '/bin/sh -c '"'"'rm -f -r /tmp/.ansible.cpdir/.ansible/tmp/ansible-tmp-1677492177.1889136-2686715-267277970132968/ > /dev/null 2>&1 && sleep 0'"'"''
<rac2> (1, b'\r\n{"changed": true, "stdout": "Please install openssl 1.0.2.2001 and higher version.\\nYou can download and install latest openssl from AIX web download site\\nhttps://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=aixbp", "stderr": "", "rc": 1, "cmd": ["/tmp/.ansible.cpdir/dnf_installer.sh", "-d", "/tmp/.ansible.cpdir"], "start": "2023-02-27 04:02:58.632274", "end": "2023-02-27 04:02:59.192649", "delta": "0:00:00.560375", "failed": true, "msg": "non-zero return code", "invocation": {"module_args": {"_raw_params": "/tmp/.ansible.cpdir/dnf_installer.sh -d /tmp/.ansible.cpdir", "_uses_shell": false, "warn": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\r\n', b'Connection to rac2 closed.\r\n')
<rac2> Failed to connect to the host via ssh: Connection to rac2 closed.

**Comment by Bhargava250** [comment]
I have copied the script to AIX lpar and tried executing it.
# ./dnf_installer.sh -d /tmp/dnf_tmp
Please install openssl 1.0.2.2001 and higher version.
You can download and install latest openssl from AIX web download site
https://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=aixbp
# lslpp -l|grep openssl
  openssl.base             3.0.5.101  COMMITTED  Open Secure Socket Layer
  openssl.license          3.0.5.101  COMMITTED  Open Secure Socket License
  openssl.man.en_US        3.0.5.101  COMMITTED  Open Secure Socket Layer
  openssl.base             3.0.5.101  COMMITTED  Open Secure Socket Layer


Issue is occurred in dnf_installer.sh
 # Check openssl version.
ssl_ver=$(lslpp -Lc openssl.base | /usr/bin/awk 'FNR==2' | /usr/bin/awk -F':' '{print $3}')
f1=$(echo $ssl_ver | /usr/bin/cut -d"." -f1)
f2=$(echo $ssl_ver | /usr/bin/cut -d"." -f2)
f3=$(echo $ssl_ver | /usr/bin/cut -d"." -f3)
f4=$(echo $ssl_ver | /usr/bin/cut -d"." -f4)
if [[ ( ! $f1 -ge 1 ) || ( ! $f2 -ge 0 ) || ( ! $f3 -ge 2 ) || **( ! $f4 -ge 2001 ) ]]**
then
    echo "Please install openssl 1.0.2.2001 and higher version."
    echo "You can download and install latest openssl from AIX web download site"
    echo "https://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=aixbp"
    exit 1
fi



Debug of shell script
+ echo 3.0.5.101
f1=3
+ + /usr/bin/cut -d. -f2
+ echo 3.0.5.101
f2=0
+ + /usr/bin/cut -d. -f3
+ echo 3.0.5.101
f3=5
+ + /usr/bin/cut -d. -f4
+ echo 3.0.5.101
f4=101
+ [[ ! 3 -ge 1 ]]
+ [[ ! 0 -ge 0 ]]
+ [[ ! 5 -ge 2 ]]
+ [[ ! 101 -ge 2001 ]]
+ echo Please install openssl 1.0.2.2001 and higher version.
Please install openssl 1.0.2.2001 and higher version.
+ echo You can download and install latest openssl from AIX web download site
You can download and install latest openssl from AIX web download site
+ echo https://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=aixbp
https://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=aixbp
+ exit 1

**Comment by Bhargava250** [comment]
We want two things to be fixed here 
1) When dnf is not configured the bootstrap playbook execution needs to be failed.
2) Update the dnf_installer.sh script with proper fix in power_aix collection

**Comment by nitismis** [comment]
Done. Updated the new bootstrap role.
