### ISSUE TITLE
New Bosboot module for AIX

### ISSUE THREAD

**Issue by nitismis** [IBM/ansible-power-aix#292]
Bosboot command: Creates a boot image. Machine needs to reboot.

**Comment by schamola** [comment]
User Inputs (attributes):
------------

1. disk_device (-d) [string var]: Validate with "lsvg -m rootvg". This command displays a map of all logical volumes. The default boot logical volume is d5.
				     This will be optional flag, When the device is not specified with the -d flag, the bosboot command assumes the default device is the disk the system is booted from.

2. prototype_file (-p) [string var]: If the prototype file is specified with -p flag, the device must also be specified with -d flag. This should be validated in the main function before any execution. Optional flag

3. only_verify (-v) [boolean var]: Verify, but do not build boot image.

4. create_image (-a) [boolean var]: Creates complete boot image and device. "-a" and "-v" cant be provided/unprovided together. Validate in main function.

5. image_name (-b) [string var]: Name of the boot image name. Optional Flag

6. table_entry (-M) choices ['primary', 'standby', 'both']: Specifies which boot pointer table entry to update.

7. platform_type (-T) [string var]: Specifies the hardware platform type (see note 6). This causes the bosboot command to create a boot image for the hardware platform type specified. If the type is not specified, the bosboot command creates a boot image whose hardware platform type matches that of the currently running machine. This flag is optional.

8. increase_space (boolean): take user permission to increase the file space.


Checks:
-------

1. Validate disk_device.
2. If prototype_file is true then disk_device must be true.
3. "-a" and "-v" cant be provided/unprovided together.
4. Validate supported platform type.
5. Check the "/tmp" disk space and disk_device space with "-q" flag. "-q" determines how much disk space is required in which file system to create the boot image.


Module:
--------

1. Documents as per above description.
2. Example playbooks/tasks.
3. validate_disk_device()
4. validate_platform()
5. validate_tmp_space()
6. determine_required_space()
7. validate_disk_space()
8. create_image()
9. increase_disk_space()
10. main()

**Comment by nitismis** [comment]
This issue was opened just to track an already closed PR #282
