### ISSUE TITLE
Please add modules for hdcryptmgr and keysvrmgr

### ISSUE THREAD

**Issue by scentoni** [IBM/ansible-power-aix#293]
We would like to enable volume encryption in our AIX VMs in IBM Cloud, with the keys stored in HPCS or Key Protect, as IBM describes in [Integrating Power Systems Virtual Server with IBM Key Management Services](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-integrate-hpcs). The tools needed for this in AIX include the commands [hdcryptmgr](https://www.ibm.com/docs/en/aix/7.3?topic=h-hdcryptmgr-command) and [keysvrmgr](https://www.ibm.com/docs/en/aix/7.3?topic=k-keysvrmgr-command). We would like to do this with custom modules instead of using [ansible.builtin.command](ansible.builtin.command) or [ansible.builtin.shell](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html) with complex logic to ensure idempotency. 

For our corresponding Linux needs, we will probably make use of [community.crypto.luks_device ](https://docs.ansible.com/ansible/latest/collections/community/crypto/luks_device_module.html).

**Comment by nitismis** [comment]
We are planning to include a module for Physical volume encryption in our next major release.

**Comment by scentoni** [comment]
Thanks, that's good to know, but will this also support encryption of logical volumes and volume groups? Do you have an ETA for this release?

**Comment by nitismis** [comment]
The module has been merged in the collection. You can test the prototype now before the formal release of the collection.
Let us know if you want any enhancement in the module or any other potential gaps. Closing the issue for now.

Thanks,

**Comment by scentoni** [comment]
Are you referring to [pull request #355](https://github.com/IBM/ansible-power-aix/pull/355)? I don't see anything in that PR relating to IBM Cloud [Key Protect](https://cloud.ibm.com/apidocs/key-protect), [Hyper Protect Crypto Services](https://cloud.ibm.com/apidocs/hs-crypto), or any other key management system.

**Comment by nitismis** [comment]
@scentoni
sorry for coming late on this.
This whole functionality of encryption, key management and facts are planned in stages. We have already provided the encryption/decryption functionality. Key management and facts are planned for upcoming releases.

Thanks
