### ISSUE TITLE
Mount module should be able to mount a directory even if it has not been exported by the user.

### ISSUE THREAD

**Issue by schamola** [IBM/ansible-power-aix#295]
**Is your feature request related to a problem? Please describe.**
When NFS mount is performed, If the directory has not been exported explicitly by the user on the NFS server, It gives an error.

**Describe the solution you'd like**
Mount module should be able to mount the directory even if it has not been exported by the user. It should add the directory to the exports file and run exportfs command to make it available for mounting on the NFS client.

**Comment by nitismis** [comment]
Not necessary
