### ISSUE TITLE
alt_disk_copy() missing 1 required positional argument: 'allow_old_rootvg'

### ISSUE THREAD

**Issue by virtualkarthik** [IBM/ansible-power-aix#298]
The alt_disk module copy action fails with the error: missing 1 required positional argument: 'allow_old_rootvg'.. The Code i used is the below.

- name: Creating alt_disk_copy on "{{ alt_disk }}"
  ibm.power_aix.alt_disk:
    action: copy
    targets: "{{ alt_disk }}"
    force: true
    

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - AIX 7.2.0.0
 - AIX 7200-05-05-2246
 - Python Version: 3.7.9   GCC 8.3.0quit
 - 
 - OpenSSH Version: 7.4pl
 - Ansible Version: 2.9.27 - Python 2.7.5

**Additional context**

**Comment by schamola** [comment]
Hi @virtualkarthik 
We will look into the issue and let you know.

**Comment by nitismis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defects support of github issues for power_aix collection.](https://trello.com/c/UkDoQL0B/9-defects-support-of-github-issues-for-poweraix-collection)

**Comment by virtualkarthik** [comment]
Is this fixed.. I still see the same error, Even after pulling the code from Galaxy forcefully

#ansible-galaxy collection install -f ibm.power_aix
Process install dependency map
Starting collection install process
Installing 'ibm.power_aix:1.6.1' to '/home/ansible/.ansible/collections/ansible_collections/ibm/power_aix'


Playbook Error
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: alt_disk_copy() missing 1 required positional argument: 'allow_old_rootvg'

**Comment by schamola** [comment]
Hi @virtualkarthik 
After the code changes, it is working fine for us. Attaching the output below.

PLAY [Alt_Disk in AIX] *************************************************************************************************************************************

TASK [Creating alt_disk_copy on a disk] ********************************************************************************************************************
[WARNING]: Platform aix on host root@XXXXXXXXXX is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information.
changed: [root@XXXXXXXXXX]

TASK [Perform a cleanup of any existing alternate disk copy] ***********************************************************************************************
changed: [root@XXXXXXXXXX]

PLAY RECAP *************************************************************************************************************************************************
root@XXXXXXXXXX : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by schamola** [comment]
Hi @virtualkarthik 
You need to copy the module  from our GitHub repo, as we have not released the newer version on galaxy as of now.

**Comment by virtualkarthik** [comment]
Thanks @schamola ,, Any ETA when it will be published in Galaxy ?
