### ISSUE TITLE
EMGR LIST Failing

### ISSUE THREAD

**Issue by virtualkarthik** [IBM/ansible-power-aix#300]
**Describe the bug**
I try to list all the efixes on a system and remove them all with the below play 

**To Reproduce**
- name: Listing all INTERIM FIXES on the Server
  ibm.power_aix.emgr:
    action: list
  register: emgrout
- debug:
    msg: "Below are the list of eFixes found in the system \n {{ emgrout.stdout }}"
- name: Removing all the INTERIM FIXES on the Server
  ibm.power_aix.emgr:
   action: remove

**Expected behavior**
List of efixes on the system like a emgr -l and removes all the efixes on the system.

**Screenshots**
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1685609284.98-15442-223795098634079/AnsiballZ_emgr.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1685609284.98-15442-223795098634079/AnsiballZ_emgr.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1685609284.98-15442-223795098634079/AnsiballZ_emgr.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.emgr', init_globals=None, run_name='__main__', alter_sys=True)
  File "/opt/freeware/lib64/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/freeware/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/freeware/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ibm.power_aix.emgr_payload_tobqkk95/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 591, in <module>
  File "/tmp/ansible_ibm.power_aix.emgr_payload_tobqkk95/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 582, in main
  File "/tmp/ansible_ibm.power_aix.emgr_payload_tobqkk95/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 315, in parse_ifix_details
IndexError: list index out of range
fatal: [unix_test3.xxx.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to unix_test3.xxxx.com closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1685609284.98-15442-223795098634079/AnsiballZ_emgr.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1685609284.98-15442-223795098634079/AnsiballZ_emgr.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1685609284.98-15442-223795098634079/AnsiballZ_emgr.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.emgr', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/opt/freeware/lib64/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/opt/freeware/lib64/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/opt/freeware/lib64/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ibm.power_aix.emgr_payload_tobqkk95/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py\", line 591, in <module>\r\n  File \"/tmp/ansible_ibm.power_aix.emgr_payload_tobqkk95/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py\", line 582, in main\r\n  File \"/tmp/ansible_ibm.power_aix.emgr_payload_tobqkk95/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py\", line 315, in parse_ifix_details\r\nIndexError: list index out of range\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Environment (please complete the following information):**
AIX 7.2.0.0
AIX 7200-05-05-2246
Python Version: 3.7.9 GCC 8.3.0quit
OpenSSH Version: 7.4pl
Ansible Version: 2.9.27 - Python 2.7.5

**Additional context**

**Comment by schamola** [comment]
Hi @virtualkarthik 
Please share the output of "emgr -l" from the target machine.

**Comment by virtualkarthik** [comment]
Hi @schamola,

Its fails even when there is no efixes in the system.

root@unix_test3(/)#emgr -l
There is no efix data on this system.
root@unix_test3(/)#

**Comment by schamola** [comment]
@virtualkarthik Thanks, we will look into the issue.
