### ISSUE TITLE
Asd

### ISSUE THREAD

**Issue by bogdansavu** [IBM/ansible-power-aix#304]
**Is your feature request related to a problem? Please describe.**
Our systems don't have direct Internet access and we are using a proxy server for this. It is possible to add support for proxy server?

**Describe the solution you'd like**
add an option for proxy in /opt/freeware/etc/dnf/dnf.conf
[main]
proxy=http://10.65.238.213:3128/
.....

**Comment by nitismis** [comment]
Thanks for the suggestions. We will work on this.
