### ISSUE TITLE
Step by step guide

### ISSUE THREAD

**Issue by s-man-g** [IBM/ansible-power-aix#31]
**Is your feature request related to a problem? Please describe.**
Users are frustrated that there is not a step by step guide to get them rolling. There is one on installation, but an in-depth walk-through from installation to running a playbook would be useful. Not completely comprehensive, but beyond a quick start.

**Describe the solution you'd like**

A beginning to end playbook guide for a new user. Step by step from ansible download through adding collection and configuration to playbook execution on managed nodes. 

**Describe alternatives you've considered** 
Users are using example playbooks and referencing current docs, but it's time consuming piecing it all together.

**Comment by pbfinley1911** [comment]
Hi Sam,
Please reach out if you need an environment for testing or Tower steps (optional)
