### ISSUE TITLE
Bootstrap role failed to unmount /tmp/.ansible.cpdir

### ISSUE THREAD

**Issue by Bhargava250** [IBM/ansible-power-aix#327]
**Describe the bug**
I am trying to configure dnf using the bootstrap role, in the end it failed to unmount /tmp/.ansible.cpdir filesystem. I am trying it on AIX "7300-01-02-2320"

TASK [ibm.power_aix.power_aix_bootstrap : Update "/opt/freeware/bin/python3"] ***
changed: [rac93]
changed: [rac94]

TASK [ibm.power_aix.power_aix_bootstrap : Unmount target filesystem "/tmp/.ansible.cpdir"] ***
fatal: [rac93]: FAILED! => {"changed": false, "cmd": "", "msg": "Unmount failed, Please provide mount_over_dir value to unmount.", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
fatal: [rac94]: FAILED! => {"changed": false, "cmd": "", "msg": "Unmount failed, Please provide mount_over_dir value to unmount.", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
rac93                      : ok=26   changed=14   unreachable=0    failed=1    skipped=12   rescued=0    ignored=0
rac94                      : ok=24   changed=12   unreachable=0    failed=1    skipped=14   rescued=0    ignored=0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. AIX 7.2.4.0]
 - Python Version: [e.g. 2.7.5, 3.6]
 - OpenSSH Version: [e.g. 1.0.2]
 - Ansible Version: [e.g. 2.10.7]
 - AIX Collection Version: [e.g. 1.2.1]

**Additional context**

**Comment by Bhargava250** [comment]
Manual "umount /tmp/.ansible.cpdir" is working fine

**Comment by nitismis** [comment]
Reopening this issue.
