### ISSUE TITLE
error is not reported in filesystem module

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#329]
Trying to expand a filesystem got OK and the filesystem is not expanded.

Playbook:

```yaml
  tasks:
  - name: expand filesystem
    ibm.power_aix.filesystem:
      filesystem: /lv01
      attributes: size=+1G
      state: present
```

Output:

```
TASK [expand filesystem] ****************************************************************************************************************************
ok: [localhost]
```

Filesystem before calling ansible-playbook was 1GB and after it is still 1GB:
```
# df -g /lv01
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/lv01          1.00      0.99    1%        4     1% /lv01
```

In the output the module reports that no changes are needed:
```json
ok: [localhost] => {
    "out": {
        "ansible_facts": {
            "discovered_interpreter_python": "/opt/freeware/bin/python3.9"
        },
        "changed": false,
        "cmd": "chfs -a size=+1G  /lv01",
        "failed": false,
        "msg": "No changes needed in /lv01",
        "rc": 0,
        "stderr": "",
        "stderr_lines": [],
        "stdout": "",
        "stdout_lines": [],
        "warnings": [
            "Platform aix on host localhost is using the discovered Python interpreter at /opt/freeware/bin/python3.9, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.14/reference_appendices/interpreter_discovery.html for more information."
        ]
    }
}
```

In reality if I execute the command from "cmd" the following error is returned:

```
# chfs -a size=+1G  /lv01
0516-787 extendlv: Maximum allocation for logical volume lv01
        is 4.
```

The error is ignored by the module and does not lead to FAIL as it should.

**Environment (please complete the following information):**
 - OS: AIX 7.3 TL1 SP1
 - Python Version: 3.9
 - OpenSSH Version: 8.1.102.2106
 - Ansible Version: 2.14.2
 - AIX Collection Version: 1.6.4

**Additional context**
In filesystem.py, function chfs(), lines 333 and further you execute chfs, then got the properties of the filesystem and compare them to the previous set of the properties. If they are the same, you suppose that nothing is changed and go away without checking any error conditions. If chfs throws an error, it is obvious that the filesystem is not changed. But there are errors which mean "there is nothing to change" and there are errors which mean "you entered something wrong". The second type of errors must be reported back to the user.

**Comment by nitismis** [comment]
Hi @aklyachkin !
Can you also paste the return code when you are running the command from "cmd".
We will look into it. Thanks for reporting the issue !

**Comment by aklyachkin** [comment]
Hi @nitismis!

The return code is 1:

```
# chfs -a size=+1G  /lv01
0516-787 extendlv: Maximum allocation for logical volume lv01
        is 4.
# echo $?
1
```

The problem is easy to reproduce on each AIX box:

- create a filesystem
- look how much LPs the filesystem has - lslv lv01 | grep LPs
- set max LPs to the value of LPs - chlv -x <number-of-lps> lv01
- try to expand the filesystem

In "normal" AIX circumstances an administrator will increase number of max LPs (chlv -x) before expanding the filesystem.

**Comment by nitismis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defects support of github issues for power_aix collection.](https://trello.com/c/UkDoQL0B/9-defects-support-of-github-issues-for-poweraix-collection)
