### ISSUE TITLE
Documentation is too old on https://ibm.github.io/ansible-power-aix

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#330]
**Describe the bug**
The documentation is not for the latest version. Please publish new documentation.

**To Reproduce**
Go to https://ibm.github.io/ansible-power-aix and switch to Release Note (direct link - https://ibm.github.io/ansible-power-aix/release_notes.html). The latest version is 1.5.0. If you look at repo - https://github.com/IBM/ansible-power-aix/blob/dev-collection/docs/source/release_notes.rst the latest version is 1.6.4.

**Expected behavior**
Latest documentation is available on https://ibm.github.io/ansible-power-aix

**Comment by nitismis** [comment]
Hi @aklyachkin 
New documentation is available here: https://github.com/IBM/ansible-power-aix/blob/dev-collection/docs/source/release_notes.rst
Not sure why it is not showing here: https://ibm.github.io/ansible-power-aix/release_notes.html
Do you have any idea if we are missing anything ?

**Comment by aklyachkin** [comment]
It looks like the action https://github.com/IBM/ansible-power-aix/actions/workflows/pages/pages-build-deployment didn't start since one year. 
I don't see the settings for repo, but I'd assume that the documentation is published from gh-pages branch and it is generated by the action. Can you please start the action manually?

**Comment by nitismis** [comment]
Hi @aklyachkin 
I tried running it manually but I am getting this error:

Error: .github#L1
jamesives/github-pages-deploy-action@v4 is not allowed to be used in IBM/ansible-power-aix. Actions in this workflow must be: within a repository owned by IBM, created by GitHub, verified in the GitHub Marketplace, or matching the following: julia-actions/*, softprops/action-gh-release@*, JuliaRegistries/TagBot@*, helm/*, golangci/golangci-lint-action@*, pypa/*, fkirc/skip-duplicate-actions@*, codespell-project/actions-codespell@v1, gaurav-nelson/github-action-markdown-link-check@v1, crazy-max/ghaction-import-gpg@*, norio-nomura/action-swiftlint@*, maxim-lobanov/setup-xcode@*.

Need to work on this.

**Comment by aklyachkin** [comment]
Help came from other side :-) Red Hat updated Ansible Galaxy and the updated documentation is available now directly on Galaxy: https://galaxy.ansible.com/ui/repo/published/ibm/power_aix/docs/

**Comment by nitismis** [comment]
Hi @aklyachkin 
 I didn't get you. This link was always working:  https://galaxy.ansible.com/ui/repo/published/ibm/power_aix/docs/ 
Still this link is showing 1.5.0 only:  https://ibm.github.io/ansible-power-aix/release_notes.html
Need to work on it.
What are you suggesting ?

Thanks

**Comment by neikei** [comment]
The last deployment of github pages with the documentation is outdated. Please check the github pages generation, the online version was generated on "Jul 12, 2022". On the other hand the documentation on Ansible Galaxy was released a few days ago and represents the current state: https://galaxy.ansible.com/ui/repo/published/ibm/power_aix/docs/

**Comment by nitismis** [comment]
@aklyachkin , @neikei 
This issue is fixed now. Closing.
Thanks for the info and reporting the issue.
