### ISSUE TITLE
Problem with module nim_flrtvc

### ISSUE THREAD

**Issue by christophegehin** [IBM/ansible-power-aix#332]
**Describe the bug**
Unable to use module nim_flrtvc

**To Reproduce**
Execute that playbook : 
  - name: test nim update standalone
    ibm.power_aix.nim_flrtvc:
      targets: netapp7n05m
      apar: all
      check_only: True
      path: /tmp
      save_report: True
      verbose: True
    register: result

**Expected behavior**
Module working and get the reports

** Error **
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] A file or directory in the path name does not exist.: '/tmp/work/FLRTVC-latest.zip'
fatal: [lab28059]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/opt/freeware/bin/python3.9"}, "changed": false, "module_stderr": "Shared connection to lab28059 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1694026863.630002-3968675-40385150950181/AnsiballZ_nim_flrtvc.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1694026863.630002-3968675-40385150950181/AnsiballZ_nim_flrtvc.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1694026863.630002-3968675-40385150950181/AnsiballZ_nim_flrtvc.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.nim_flrtvc', init_globals=dict(_module_fqn='ansible_collections.ibm.power_aix.plugins.modules.nim_flrtvc', _modlib_path=modlib_path),\r\n  File \"/opt/freeware/lib64/python3.9/runpy.py\", line 225, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/opt/freeware/lib64/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/opt/freeware/lib64/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ibm.power_aix.nim_flrtvc_payload_pa8ukmf9/ansible_ibm.power_aix.nim_flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_flrtvc.py\", line 1667, in <module>\r\n  File \"/tmp/ansible_ibm.power_aix.nim_flrtvc_payload_pa8ukmf9/ansible_ibm.power_aix.nim_flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_flrtvc.py\", line 1590, in main\r\n  File \"/tmp/ansible_ibm.power_aix.nim_flrtvc_payload_pa8ukmf9/ansible_ibm.power_aix.nim_flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_flrtvc.py\", line 496, in unzip\r\n  File \"/opt/freeware/lib64/python3.9/zipfile.py\", line 1248, in __init__\r\n    self.fp = io.open(file, filemode)\r\nFileNotFoundError: [Errno 2] A file or directory in the path name does not exist.: '/tmp/work/FLRTVC-latest.zip'[\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)

[**Environment (please complete the following information):**](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)
[- OS: 7.2.5.6](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)
[- Python Version: python3.9-3.9.17-1](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)
[- OpenSSH Version: 8.1.112.1201](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)
[- Ansible Version: 2.14.2](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)
[- AIX Collection Version: 1.6.4](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)

[**Additional context**](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)
[I don](http://r/n%22,%20%22msg%22:%20%22MODULE%20FAILURE/nSee%20stdout/stderr%20for%20the%20exact%20error%22,%20%22rc%22:%201%7d%0d%0d%0d%0d**Environment%20(please%20complete%20the%20following%20information):**%0d-%20OS:%207.2.5.6%0d-%20Python%20Version:%20python3.9-3.9.17-1%0d-%20OpenSSH%20Version:%208.1.112.1201%0d-%20Ansible%20Version:%202.14.2%0d-%20AIX%20Collection%20Version:%201.6.4%0d%0d**Additional%20context**%0dI%20don)'t have the problem with ansible module flrtvc. That module uses that url to download the file FLRTVC-latest.zip : https://esupport.ibm.com/customercare/sas/f/flrt3/FLRTVC-latest.zip, as you can see in the code of the module : 
    if not download('https://esupport.ibm.com/customercare/sas/f/flrt3/FLRTVC-latest.zip',
                    flrtvc_dst, resize_fs):

The module nim_flrtvc use that url : https://esupport.ibm.com/customercare/sas/f/flrt3/FLRTVC-latest, as you can see in the code of the module : 
    if not download(module, results['meta'],
                    'https://esupport.ibm.com/customercare/sas/f/flrt3/FLRTVC-latest',

Could you change the url in the module nim_flrtvc please ? 

Regards

**Comment by nitismis** [comment]
Thanks for reporting this.
This change in URL is recent, we updated in flrtvc but somehow missed in NIM.
We will update that.

Thanks !
