### ISSUE TITLE
doc: ibm/power_aix/modules/installp examples may refer to ansible's os/installp not ibm.power_aix

### ISSUE THREAD

**Issue by dpkshetty** [IBM/ansible-power-aix#34]
**Describe the bug**
ibm/power_aix/modules/installp examples may refer to ansible's os/installp not ibm.power_aix

**To Reproduce**
1. https://ibm.github.io/ansible-power-aix/modules/installp.html
2. Copy any example
3. It works but then its actually using ansible's built-in OS module's installp, not ibm.power_aix.installp 
4. No error seen and User may mistakenly think that they are using  ibm.power_aix.installp and may further get confused as os/installp and  ibm.power_aix.installp arguments/parameters are way different.

**Expected behavior**
All examples should use fully qualified module path ( ibm.power_aix.installp )

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. AIX 7.2.4.0]
 - Python Version [e.g. 2.7.5, 3.6]
 - OpenSSH Version [e.g. 1.0.2]

**Additional context**

**Comment by pbfinley1911** [comment]
The changes have been approved and will be present in the upcoming release (Sept 28th)
