### ISSUE TITLE
Release 1.7.0 is not listed as Github release

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-aix#359]
Unfortunately the new release is not listed yet and a download via github is not possible. Download via Ansible Galaxy worked and we are happy to be able to test the new version. 🚀 

https://github.com/IBM/ansible-power-aix/blob/119592f8395126206699bc0050a61a78abec5355/docs/source/release_notes.rst?plain=1#L41

If someone needs a download link with Github as source: https://github.com/IBM/ansible-power-aix/raw/dev-collection/builds/ibm-power_aix-1.7.0.tar.gz

**Comment by nitismis** [comment]
It takes sometime to get approval on Red Hat Automation hub. I see the link of github to download the tar file is not working. Let me update the link with what you have provided above.

**Comment by nitismis** [comment]
okay !! github link is fixed now.
