### ISSUE TITLE
Missing repository for the latest release

### ISSUE THREAD

**Issue by lewus** [IBM/ansible-power-aix#365]
**Describe the bug**
Missing repository for the latest release

**To Reproduce**
1. Go to https://galaxy.ansible.com/ui/repo/published/ibm/power_aix/
2. Check the latest version (it is 1.7.0)
3. Go to https://github.com/IBM/ansible-power-aix/releases
4. Check the latest release (it is 1.6.1)

**Expected behavior**
The latest release should have a repository

**Screenshots**
none

**Environment (please complete the following information):**
all

**Additional context**
Looks like there are no repositories since release 1.6.1 which was 5 months ago

**Comment by nitismis** [comment]
Thanks for reporting this. Updated !!
