### ISSUE TITLE
update from lpp source not working

### ISSUE THREAD

**Issue by thomasbettray** [IBM/ansible-power-aix#370]
**Describe the bug**
nim module "update" action fails to update a nim client from lpp_source with message displayed below. 

**To Reproduce**
Use this playbook.yml:

- hosts: nimclient
  tasks:
  - name: Update existing packages using the additional_software lpp_source
    ibm.power_aix.nim:
      action: update
      lpp_source: mylppsource
      targets: "{{ inventory_hostname }}"
    delegate_to: nimserver
    remote_user: ansibleuser
    become: yes

Run playbook:
ansible-playbook -v -i inventories/abc.ini playbook.yml

**Expected behavior**
This should update the nimclient from nimserver, using the given lpp_source. This used to work some time ago, but with update as of 2.11.2023, this fails. 

**Screenshots**
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'unavail_targets' referenced before assignment
fatal: [nimclient -> nimserver(None)]: FAILED! => changed=false
  module_stderr: |-
    Shared connection to 10.7.1.19 closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/home/ansible/.ansible/tmp/ansible-tmp-1698932022.396688-22675762-147084550653256/AnsiballZ_nim.py", line 107, in <module>
        _ansiballz_main()
      File "/home/ansible/.ansible/tmp/ansible-tmp-1698932022.396688-22675762-147084550653256/AnsiballZ_nim.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ansible/.ansible/tmp/ansible-tmp-1698932022.396688-22675762-147084550653256/AnsiballZ_nim.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.nim', init_globals=dict(_module_fqn='ansible_collections.ibm.power_aix.plugins.modules.nim', _modlib_path=modlib_path),
      File "/usr/opt/python3/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/opt/python3/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/opt/python3/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ibm.power_aix.nim_payload_66gl3_z2/ansible_ibm.power_aix.nim_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim.py", line 2071, in <module>
      File "/tmp/ansible_ibm.power_aix.nim_payload_66gl3_z2/ansible_ibm.power_aix.nim_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim.py", line 1994, in main
      File "/tmp/ansible_ibm.power_aix.nim_payload_66gl3_z2/ansible_ibm.power_aix.nim_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim.py", line 978, in nim_update
    UnboundLocalError: local variable 'unavail_targets' referenced before assignment
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Environment (please complete the following information):**
 - OS: AIX 7300-01-02-2320 on both, nimclient and nimserver
 - Python Version: 3.9.12
 - OpenSSH Version: 9.2.112.2000
 - Ansible Version: ansible-core-2.14.2-1.noarch, ansible-7.2.0-1.noarch
 - AIX Collection Version: 1.7.2

Error seems to be due to an uninitialized variable in 
~/.ansible/collections/ansible_collections/ibm/power_aix/plugins/modules/nim.py, line 975. Adding the following two lines in line 977 fixes the error:

    else:
        unavail_targets = ''

This used to work before our latest update, but I am not sure on which version we were before.

**Comment by Rich-J-AIX** [comment]
I was just about to report the same issue!
From tests I believe it was introduced at v1.6
The existing logic only works if  "alt_disk_update_name" is passed to the module.

However, when passing "alt_disk_update_name" it runs a test for the disk on the NIM client which also fails.
The check runs:
 `lspv {alt_disk_update_name}` 
 on the client which then gives an error: 
` msg: Following targets does not have specified alt_disk_update_name disk:['r', 'j', '-', 'a', 'i', 'x', '-', 'v', 'm', '-', '2', 'r', 'j', '-', 'a', 'i', 'x', '-', 'v', 'm', '-', '3']
`
I'm not sure if the test is faulty or some other logic needs to be passed to the module:
e.g.  `lspv hdisk1`
if hdisk1 is not in an existing active VG lspv gives an error, but if it is in an existing VG then it is not available for an alt_disk upgrade!

**Comment by nitismis** [comment]
Hi !
Sorry guyz .. I was on vacation !
@thomasbettray , thanks for reporting this issue.
@Rich-J-AIX , thanks for digging deeper... at first sight it seems that there is some logical issue. Need to work on that.
@schamola, Please look into this.

Thanks

**Comment by Rich-J-AIX** [comment]
I have worked on a branch for this and a fix for the alt_disk issue (added [@thomasbettray](https://github.com/thomasbettray)'s coding from above).
Update to an alt_disk now working with my version.

N.B. Documentation should also be updated to say python3 required
 - Not sure if coding could be included in the module to report if incorrect version rather than getting lots of python failures?

Happy to do a pull request if you want to see my coding:
https://github.com/Rich-J-AIX/ansible-power-aix/blob/dev-collection/plugins/modules/nim.py

**Comment by nitismis** [comment]
@Rich-J-AIX , Can we close this now ? I have merged your PR

**Comment by Rich-J-AIX** [comment]
Many thanks Nitish. 
Happy to close - and although this one is actually @thomasbettray's issue - I did include the code he suggested. 
BtW - It possibly also covers issue #366
