### ISSUE TITLE
Add output from "lsrsrc IBM.MCP" to lpar_facts to make the controlling HMC details readily available from within a Playbook.

### ISSUE THREAD

**Issue by SteveMunday62** [IBM/ansible-power-aix#374]
I'd like to request that the output from the `lsrsrc IBM.MCP` command be added to lpar_facts so that the HMC controlling a given LPAR is easily retrievable from within a Playbook.

Many thanks, Steve

**Comment by nitismis** [comment]
Sure Steve. Thanks for the suggestion.

**Comment by SteveMunday62** [comment]
Guys, any news as to when the extra (HMC) details will be available via lpar_facts please?

Many thanks, Steve

**Comment by schamola** [comment]
Hi @SteveMunday62 
You can expect this enhancement to be available by our next release (planned for May end)

**Comment by SteveMunday62** [comment]
Excellent, thanks very much guys.

Steve
#IBMChampion

**Comment by nitismis** [comment]
PR merged for this feature. Closing the issue.
