### ISSUE TITLE
`alt_disk` module doesn't work with `install` action

### ISSUE THREAD

**Issue by dmnagornyi** [IBM/ansible-power-aix#375]
**Describe the bug**
When `action` is set to `install` task fails with error.
```
"cmd": "-b + update_all -l /path -d hdisk0",
"msg": "[Errno 2] A file or directory in the path name does not exist.: b'-b'",
```

I don't see `alt_disk_copy` command in the module's source code: https://github.com/IBM/ansible-power-aix/blob/73142877d67e349e41fba715657a8e857f88728e/plugins/modules/alt_disk.py#L641C5-L641C13

**To Reproduce**
Create simple playbook with `ibm.power_aix.alt_disk` module and set action to `install`

**Expected behavior**
Module should run the command `alt_disk_copy` with extra arguments based on module parameters

**Environment:**
 - OS: AIX 7.2.0.0
 - Python Version: 3.9.16
 - OpenSSH Version: 1.0.2
 - Ansible Version: 2.15.5
 - AIX Collection Version: 1.7.2

**Comment by dmnagornyi** [comment]
https://github.com/IBM/ansible-power-aix/pull/378

**Comment by nitismis** [comment]
Have merged the PR: https://github.com/IBM/ansible-power-aix/pull/378. Closing the issue now.
