### ISSUE TITLE
can't find user module

### ISSUE THREAD

**Issue by takizan** [IBM/ansible-power-aix#38]
There is user module in the document [here](https://ibm.github.io/ansible-power-aix/modules/user.html).
But ibm.power_aix collections 1.0.2 has no user module.
Where is the user module for aix?

**Comment by pbfinley1911** [comment]
Hi, the user module hasn't been upstream to the Galaxy community.. not yet.  New modules will be added in the upcoming 1.1.0 version (end of Sept).

Keep in mind that the documentation isn't limited to Galaxy content.  It includes modules/content found within the Git project space as well.  So, it's best to check the Content tab within the Galaxy power_aix space.
