### ISSUE TITLE
Feature Request: Add getconf module

### ISSUE THREAD

**Issue by syahrul-aiman** [IBM/ansible-power-aix#399]
**Is your feature request related to a problem? Please describe.**
Currently, only able to get system configuration variable values by using `shell` module or `command` module.

**Describe the solution you'd like**
`getconf` module that will retrieve system configuration variable values as faacts

**Describe alternatives you've considered**
using `shell` module or `command` module to execute the following:
```shell
$ getconf -a
```

**Comment by nitismis** [comment]
Merged the PR.
