### ISSUE TITLE
Python Error when using suma.py module

### ISSUE THREAD

**Issue by kvangogh** [IBM/ansible-power-aix#40]
Using Ansible 2.9 and Python 3.6.8
Problem:
when trying to use suma module to download service pack to aix endpoint getting the following python output ending in a python error:
  **ValueError: too many values to unpack**

[root@POWERVCLAB1 aix]# ansible-playbook aix_suma.yml

PLAY [NIM check for system updates] ************************************************************************************

TASK [check initial oslevel] *******************************************************************************************
ok: [ansible-vm1]

TASK [debug] ***********************************************************************************************************
ok: [ansible-vm1] =>
  initial_oslevel:
    ansible_facts:
      discovered_interpreter_python: /usr/bin/python
    changed: false
    cmd: oslevel -s
    delta: '0:00:01.818279'
    end: '2020-09-24 08:45:56.483716'
    failed: false
    rc: 0
    start: '2020-09-24 08:45:54.665437'
    stderr: ''
    stderr_lines: []
    stdout: 7100-05-03-1846
    stdout_lines:
    - 7100-05-03-1846

TASK [create temp filesystem for suma updates] *************************************************************************
changed: [ansible-vm1]

TASK [debug] ***********************************************************************************************************
ok: [ansible-vm1] =>
  results:
    changed: true
    failed: false
    msg: Modification of Filesystem '/export/backups/suma_download' completed

TASK [mount new filesystem] ********************************************************************************************
ok: [ansible-vm1]

TASK [debug] ***********************************************************************************************************
ok: [ansible-vm1] =>
  suma_output:
    changed: false
    failed: false
    msg: Filesystem/Mount point '/export/backups/suma_download' already mounted

TASK [check oslevel] ***************************************************************************************************
ok: [ansible-vm1]

TASK [debug] ***********************************************************************************************************
ok: [ansible-vm1] =>
  new_oslevel:
    changed: false
    cmd: oslevel -s
    delta: '0:00:01.817289'
    end: '2020-09-24 08:46:02.432532'
    failed: false
    rc: 0
    start: '2020-09-24 08:46:00.615243'
    stderr: ''
    stderr_lines: []
    stdout: 7100-05-03-1846
    stdout_lines:
    - 7100-05-03-1846

PLAY RECAP *************************************************************************************************************
ansible-vm1                : ok=8    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[root@POWERVCLAB1 aix]# vim aix_suma.yml
[root@POWERVCLAB1 aix]# ansible-playbook aix_suma.yml

PLAY [NIM check for system updates] ************************************************************************************

TASK [check initial oslevel] *******************************************************************************************
ok: [ansible-vm1]

TASK [create temp filesystem for suma updates] *************************************************************************
changed: [ansible-vm1]

TASK [mount new filesystem] ********************************************************************************************
ok: [ansible-vm1]

TASK [AIX SUMA preview] ************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: too many values to unpack
fatal: [ansible-vm1]: FAILED! => changed=false
  module_stderr: |-
    Shared connection to ansible-vm1 closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/.ansible/tmp/ansible-tmp-1600962524.8442993-25375-155387106713494/AnsiballZ_suma.py", line 102, in <module>
        _ansiballz_main()
      File "/.ansible/tmp/ansible-tmp-1600962524.8442993-25375-155387106713494/AnsiballZ_suma.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/.ansible/tmp/ansible-tmp-1600962524.8442993-25375-155387106713494/AnsiballZ_suma.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.suma', init_globals=None, run_name='__main__', alter_sys=True)
      File "/opt/freeware/lib/python2.7/runpy.py", line 176, in run_module
        fname, loader, pkg_name)
      File "/opt/freeware/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/opt/freeware/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_suma_payload__YD5_T/ansible_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 869, in <module>
      File "/tmp/ansible_suma_payload__YD5_T/ansible_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 859, in main
      File "/tmp/ansible_suma_payload__YD5_T/ansible_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 669, in suma_download
    **ValueError: too many values to unpack**
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *************************************************************************************************************
ansible-vm1                : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Here is the playbook content: 

[root@POWERVCLAB1 aix]# cat aix_suma.yml
---
- name: "NIM check for system updates"
  hosts: ansible-vm1
  gather_facts: no

  collections:
  - ibm.power_aix

  vars:
    suma_action: preview
    suma_targets: ansible-vm1
    suma_oslevel: latest
    suma_download_dir: /export/backups/suma_download
#    vm_targets: ansible_vm1

  tasks:

    - name: check initial oslevel
      shell: "oslevel -s"
      register: initial_oslevel
      changed_when: false

#    - debug: var=initial_oslevel

    - name: create temp filesystem for suma updates
      filesystem:
        filesystem: "{{ suma_download_dir }}"
        attributes: size=30G
        state: present
        vg: ntestvg
        auto_mount: true
      register: results
#    - debug: var=results

    - name: mount new filesystem
      mount:
        mount_dir: "{{ suma_download_dir }}"
        state: mount

    - name: "AIX SUMA {{ suma_action }}"
      suma:
        action: "{{ suma_action }}"
        description: "{{ suma_action }} available updates"
        oslevel: "{{ suma_oslevel }}"
        download_dir: "{{ suma_download_dir }}"
      register: suma_output
    - debug: var=suma_output

    - name: check oslevel
      shell: "oslevel -s"
      register: new_oslevel
      changed_when: false

    - debug: var=new_oslevel

**Comment by robinvy** [comment]
Hi kvangogh,
Thank you for letting us know about this issue.
The fix will be part of the PR #39 (you can see the following commit if you want to fix it on your system right now: https://github.com/IBM/ansible-power-aix/pull/39/commits/afc340d1458e712efae1941376744e545e73a214 )
