### ISSUE TITLE
nim_vios_hc.py errors 

### ISSUE THREAD

**Issue by kvangogh** [IBM/ansible-power-aix#41]
Running ansible 2.9 on python 3.6.8
encountering errors when running playbook with nim_vios_hc.py module

Error:
[root@POWERVCLAB1 aix]# ansible-playbook vios_hc.yml

PLAY [VIOS health check playbook] **************************************************************************************

TASK [execute power_aix_vioshc role] ***********************************************************************************

TASK [ibm.power_aix.power_aix_vioshc : Install vioshc.py onto target] **************************************************
ok: [smopwrnimlab]

TASK [Perform a health check on VIOS] **********************************************************************************
fatal: [smopwrnimlab]: FAILED! => changed=false
  msg: 'Failed to get the VIOS information, vioshc returned: 3'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    ERROR: Failed to get NIM name for smocopwrhmc1.jhacorp.com: Not Found
  stdout_lines: <omitted>

PLAY RECAP *************************************************************************************************************
smopwrnimlab               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

log file from nim server: 
# pg vioshc_2020_09_24_161005.log
################################################################################
vioshc log file for command:
['/usr/sbin/vioshc.py', '-i', 'smocopwrhmc1', '-l', 'a']
################################################################################

Parsing command line arguments
PID=%(thread)d
Checking mandatory arguments
Getting HMC smocopwrhmc1 info
hmc smocopwrhmc1 hostname: smocopwrhmc1.jhacorp.com
command ['lsnim', '-a', 'if1'] returned:
 rc:0
 stdout:master:
   if1 = network1 smopwrnimlab.jhacorp.com FAB958849820
smoansiblelab1:
   if1 = network1 smoansiblelab1.jhacorp.com FAE465EA9220 ent0
smoansiblelab2:
   if1 = network1 smoansiblelab2.jhacorp.com FAE3AD389820 ent0
smoansiblep1:
   if1 = prodnet smoansiblep1 0
ansible-vm1:
   if1 = network1 ansible-vm1 0
smoansiblep3:
   if1 = prodnet smoansiblep3 0
ansible-vm2:
   if1 = network1 ansible-vm2 0
smopwr7e2bvios2:
   if1 = network1 smopwr7e2bvios2 0
smopwr7e2bvios1:
   if1 = network1 smopwr7e2bvios1 0
smopwr7e1bvios1:
   if1 = network1 smopwr7e1bvios1 0
smopwr7e1bvios2:
   if1 = network1 smopwr7e1bvios2 0
smocopwrhmc1:
   if1 = ent-Network1 smocopwrhmc1 0 ent

 stderr:
ERROR: Failed to get NIM name for smocopwrhmc1.jhacorp.com: Not Found
hmc smocopwrhmc1.jhacorp.com nim_name:

here is the what the hmc object looks like on the nim server: 

# lsnim -l smocopwrhmc1
smocopwrhmc1:
   class       = management
   type        = hmc
   passwd_file = /etc/sysmgt/dsm/config/smocopwrhmc1
   manages     = 7895-42X_1067E1B
   manages     = 7895-42X_1067E2B
   login       = KVanGogh
   mgmt_port   = 12443
   if1         = ent-Network1 smocopwrhmc1.jhacorp.com 0 ent
   Cstate      = ready for a NIM operation
   prev_state  = ready for a NIM operation
   Mstate      = currently running

**Comment by robinvy** [comment]
That's odd, the vioshc log file shows the `# lsnim -a if1` command result for smocopwrhmc1 is:

> if1 = ent-Network1 smocopwrhmc1 0 ent

while in the `# lsnim -l smocopwrhmc1` command on your system returns:

> if1 = ent-Network1 smocopwrhmc1.jhacorp.com 0 ent

Those output should be the same. Did you change the NIM smocopwrhmc1 object between these two command?

Note the `vioshc.py` script is expecting the full hostname (`smocopwrhmc1.jhacorp.com`) to be set in the interface (`if1`) option of the NIM object.
Please ensure it's the case, try running your playbook again and let us know.
You can check this using `# lsnim -a if1` on your NIM master.

**Comment by pbfinley1911** [comment]
Marking as stale. Please reopen when additional details are available.
