### ISSUE TITLE
LDAP check is not supported before running mkuser in user module.

### ISSUE THREAD

**Issue by sumitradawn** [IBM/ansible-power-aix#411]
"msg": "Failed to create user: aixguest, command: mkuser -R LDAP home=\"/home/test/aixguest\" data=\"1272\"  aixguest",
    "rc": 22,
    "stderr": "Invalid -R option \"LDAP\" \nUsage: mkuser [-R load_module] [-a] \"attr=value\" ... newuser\n",
    "stderr_lines": [
        "Invalid -R option \"LDAP\" ",
        "Usage: mkuser [-R load_module] [-a] \"attr=value\" ... newuser"
    ],
    "stdout": "",
    "stdout_lines": []
}

**Comment by schamola** [comment]
Thanks for reporting, we are working on it!

**Comment by nitismis** [comment]
PR is merged.
