### ISSUE TITLE
FLRT.YML ISSUE not generate and save in /usr/sys/inst.images

### ISSUE THREAD

**Issue by emersonjlima** [IBM/ansible-power-aix#423]
I spoke to 
[@sangamesh.swamy](https://ibm-cio.slack.com/team/W688ZUHMK)
 and he asked me to contact you about a way to automate some processes automatically regarding updates in both AIX and efix.
First of all, thank you for your attention. Answering your question, we are not using Ansible for this yet. I wanted to see the steps that could be done using SUMA + LIVEUPDATE + NIM MASTER + FLRTVC so that we would have a repository that was always up to date and that we could look for updates and product updates (AIX and fix) in this repository. Thank you very much in advance for your attention. I await contact.

know Ansible, however, I would like to know the lines and codes behind these solutions to be able to learn and understand how we could adapt them to our reality. Today we have 32 LPARES, I wanted to leave them all with LIVEUPDATE being updated automatically with SUMA connecting with FLRTVC. By the way, this FLRTVC.yml, this script only points out what will be updated and does not record anything in the /usr/sys/inst.images directory, it only records the flrtvc.txt. It doesn't create the work directory or tardir, it shows a in the command output, but it doesn't record, I don't know why this is happening. I'll give you the playbook code, if you can identify it and help me with this, I'd be very grateful.
3.download": [
                "/usr/sys/inst.images/work/tardir/openssh_fix15/38408m9a.230811.epkg.Z",
                "/usr/sys/inst.images/work/tardir/openssh_fix15/38408m9b.230811.epkg.Z",
                "/usr/sys/inst.images/work/tardir/openssh_fix15/38408m9c.230811.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix5/IJ47597m4a.230718.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix5/IJ47597m6a.230717.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix5/IJ47629m4a.230718.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix5/IJ47630m2a.230718.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix5/IJ47631m6a.230718.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix5/IJ47632m4a.230718.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45056m4a.230125.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45056m5a.230125.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45056m6a.230504.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45057m2a.230125.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45057m2b.230405.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45058m4a.230125.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45058m4b.230405.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45059m2a.230125.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45059m2b.230405.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45060s1a.230125.epkg.Z",
                "/usr/sys/inst.images/work/tardir/libxml2_fix4/IJ45060s2a.230504.epkg.Z"
Does not record or download the download to the directory indicated in the playbook:
[[g54pa00005640.az14.dal.cpc.ibm.com](http://g54pa00005640.az14.dal.cpc.ibm.com/):/usr/sys/inst.images] ls -ltr
total 8
-rw------- 1 root system 3403 Dec 07 11:13 flrtvc.txt
Below the code line in flrtvc.yml
---
- name: "FLRTVC on AIX playbook"
  hosts: all
  gather_facts: yes
  become: true
  become_user: root
  vars:
    apar: sec
    path: /usr/sys/inst.images
    check: no
    download_only: yes
    extend: yes
    protocol_v: "https"
    force_v: no
    clean_v: true
    verbose_v: yes
    save_report: yes
  collections:
    - ibm.power_aix
  tasks:
    - name: Install wget if it is not installed.
      import_role:
        name: power_aix_bootstrap
      vars:
        pkgtype: "wget"
    - name: "FLRTVC"
      flrtvc:
        path: "{{ path }}"
        verbose: "{{ verbose_v }}"
        apar: "{{ apar }}"
        force: "{{ force_v }}"
        clean: "{{ clean_v }}"
        check_only: "{{ check }}"
        download_only: "{{ download_only }}"
        extend_fs: "{{ extend }}"
        protocol: "{{ protocol_v }}"
        save_report: "{{ save_report }}"
      environment:
        PATH: "/usr/bin:/usr/sbin/:/opt/freeware/bin"
      register: result
    - debug: var=result
    
    We recently talked about a problem in which flrtvc.yml searches for information, but does not save it in the aforementioned directory, we had to check, but I believe that due to its demands, it ended up forgetting the fact. Could you help us try to resolve this problem? Another point, MRS TOOLS, I can't download it automatically, just by authenticating, would there be any way for this to not happen and be able to download the programs directly to the server, just like flrtvc.yml does with the efixes? Thank you in advance and I look forward to hearing from you on this matter.

**Comment by nitismis** [comment]
Sorry for being late. For anything related to playbooks, please contact IBM expert lab team. Here we are only addressing any issues/defects with our existing modules/roles. I am closing this defect.
