### ISSUE TITLE
Incorrect check of inetd services in nim_alt_disk_migration role

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#426]
**Describe the bug**
```
fatal: [nim]: FAILED! => {"changed": false, "msg": "bootpd is not active on NIM master"}
```

but bootpd is active on the system:

```
# lssrc -ls inetd | grep bootpd
 bootps       /usr/sbin/bootpd         bootpd -d /etc/bootptab  active
```

The problem is in the check which works only if there are no additional arguments added to the services:

```
/usr/bin/lssrc -ls inetd | /usr/bin/grep bootpd | /usr/bin/awk '{print $5}'
```

The result of the check is:

```
# /usr/bin/lssrc -ls inetd | /usr/bin/grep bootpd | /usr/bin/awk '{print $5}'
/etc/bootptab
```

The correct check should look like:

```
/usr/bin/lssrc -ls inetd | /usr/bin/grep bootpd | /usr/bin/awk '{print $NF}'
```

The result would be:

```
# /usr/bin/lssrc -ls inetd | /usr/bin/grep bootpd | /usr/bin/awk '{print $NF}'
active
```

**To Reproduce**
Add or remove some options to bootpd or tftpd services to change the status field number.

**Expected behavior**
The check should check status, not the value of the field number 5.

**Additional context**

File https://github.com/IBM/ansible-power-aix/blob/dev-collection/roles/nim_alt_disk_migration/tasks/validate_nim_connection.yml, lines 71 and 86. Change $5 to $NF (last field).

**Comment by nitismis** [comment]
Fixed.
