### ISSUE TITLE
unable to modify "login" and "rlogin" parameters with user module

### ISSUE THREAD

**Issue by ssouksav** [IBM/ansible-power-aix#44]
hi

I use the following code in order to change "login" and "rlogin" attributes to "false":

---
- name: MY PLAYBOOK
  hosts: LAB
  remote_user: ansible

  collections:
  - ibm.power_aix

  tasks:
  - name: change login and rlogin
    user:
      state: modify
      name: bin
      attributes:
        login: false
        rlogin: false

The ouput looks fine:
PLAY RECAP ***********************************************************************************************************************
myaix                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

But the attributes remain unchanged. Any idea?

**Comment by dberg1** [comment]
This is because you are using boolean values (false) not strings ("false").
false without the double-quotes will be expanded as "False" by Python which is not a supported `chuser` `login` or `rlogin` value.

You can change your playbook like this:
```
attributes:
  login: "false"
  rlogin: "false"
```

**Comment by dberg1** [comment]
The AIX `chuser` command simply ignores unkown values:
```
# chuser login=False rlogin=False  bin
# echo $?
0
# lsuser -a login rlogin bin
bin login=true rlogin=true
```

**Comment by ssouksav** [comment]
indeed, it's so obvious when you know the answer!

Thank you very much @dberg1 !
