### ISSUE TITLE
Errors when removing ifix (awx

### ISSUE THREAD

**Issue by alexistrate87** [IBM/ansible-power-aix#455]
Hello,

Running this ansible code for removing the ifixes:

---
  - name: "LIST IFIX on AIX server"
    shell: |
      emgr -P | grep install | awk '{print $NF}' | sort -u
    register: aix_list_ifix

  - name: "UNINSTALL IFIX on AIX server"
    ibm.power_aix.emgr:
      action: remove
      ifix_label: "{{ item }}"
    loop: "{{ aix_list_ifix.stdout_lines | flatten }}"
    register: aix_uninstall_ifix

Generates the following errror in AWX.

Failed to JSON parse a line from worker stream. Error: Expecting property name enclosed in double quotes: line 1 column 16385 (char 16384) Line with invalid JSON data: b'{"uuid": "2d13e4a0-3551-44cc-bb13-9f5ff1c85006", "counter": 1050, "stdout": "\\u001b[0;33mchanged: [gva1225] => (item=IJ41685s4a) => {\\u001b[0m\\r\\n\\u001b[0;33m \\"ansible_loop_var\\": \\"item\\",\\u001b[0m\\r\\n\\u001b[0;33m \\"changed\\": true,\\u001b[0m\\r\\n\\u001b[0;33m \\"ifix_details\\": [],\\u001b[0m\\r\\n\\u001b[0;33m \\"invocation\\": {\\u001b[0m\\r\\n\\u001b[0;33m \\"module_args\\": {\\u001b[0m\\r\\n\\u001b[0;33m \\"action\\": \\"remove\\",\\u001b[0m\\r\\n\\u001b[0;33m \\"alternate_dir\\": null,\\u001b[0m\\r\\n\\u001b[0;33m \\"bosboot\\": null,\\u001b[0m\\r\\n\\u001b[0;33m \\"commit\\": false,\\u001b[0m\\r\\n\\u001b[0;33m \\"extend_fs\\": false,\\u001b[0m\\r\\n\\u001b[0;33m \\"force\\": false,\\u001b[0m\\r\\n\\u001b[0;33m \\"from_epkg\\": false,\\u001b[0m\\r\\n\\u001b[0;33m \\"ifix_label\\": \\"IJ41685s4a\\",\\u001b[0m\\r\\n\\u001b[0;33m \\"ifix_number\\": null,\\u001b[0m\\r\\n\\u001b[0;33m \\"ifix_package\\": null,\\u001b[0m\\r\\n\\u001b[0;33m'

Any fix ideas ?

**Comment by nitismis** [comment]
Thanks for reporting. Let us investigate and we will come back.

**Comment by schamola** [comment]
Hi @alexistrate87 !
In the first task what are you trying to do, and why are you using shell and not the emgr module to achieve it ?

**Comment by schamola** [comment]
You can use the emgr module to list fixes like this:

    - name: List interim fix on the system
      ibm.power_aix.emgr:
        action: list
      register: aix_list_ifix

**Comment by nitismis** [comment]
This issue is idle for last one month, so closing. If @alexistrate87 has any update, please reopen with details.
