### ISSUE TITLE
module setup, failed when running a playbook

### ISSUE THREAD

**Issue by pablomuelainco** [IBM/ansible-power-aix#47]
Control node: Ansible 2.9
Ansible Endpoint: AIX 7.2, Python 2.7

Error: module setup, failed when running a playbook

[autom@ansible playbooks]$ ansible-playbook yum-conf.yml
[WARNING]: running playbook inside collection ibm.power_aix

PLAY [aix72] ******************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
[WARNING]: Module invocation had junk after the JSON data: usage: sudo -e [-kS] [-p prompt] [-u username|#uid] file ...

fatal: [aix72]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"failed": true, "module_stderr": "Shared connection to aix72 closed.\r\n", "module_stdout": "sudo: illegal option `-n'\r\nusage: sudo -h | -K | -k | -L | -l | -V | -v\r\nusage: sudo [-bEHkPS] [-p prompt] [-u username|#uid] [VAR=value]\r\n            {-i | -s | <command>}\r\nusage: sudo -e [-kS] [-p prompt] [-u username|#uid] file ...\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}

PLAY RECAP *************************************************************************************************************************************************************************
aix72                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[autom@ansible playbooks]$ cat yum-conf.yml
---
  - hosts: aix72
    gather_facts: yes
    become: yes
    collections:
    - ibm.power_aix

  - tasks:
     - name: Copy yum.conf
       copy:
         src: yum.conf
         dest: /opt/freeware/etc/yum/yum.conf
         owner: root
         group: system
         mode: '0644'
       register: copyf
     - name: check copy
       debug:
         msg: "{{ copyf }}"

**Comment by dberg1** [comment]
Could you please check which version of sudo is installed on the target host?
My version of sudo from AIX toolbox supports `-n` option:
```
# rpm -q sudo
sudo-1.8.31p1-1.ppc

# sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] file ...
```

**Comment by pbfinley1911** [comment]
The errors witnessed aren't specific to our collection, so we'll close at this time.
