### ISSUE TITLE
Looks like issue in reduce_vg function of lvg module

### ISSUE THREAD

**Issue by nitismis** [IBM/ansible-power-aix#481]
It looks like in lvg module reduce_vg function is not handling the failure case information properly when removing the physical volumes.
Here the problematic code snippet:
success_msg = "Physical volume(s) '%s' removed from Volume group '%s'." \
                % (' '.join(**pv_list**), vg_name)
fail_msg = "Failed to remove Physical volume(s) '%s' from Volume group '%s'." \
                % (' '.join(**pv_list**), vg_name)

In both messages same list is getting passed.
Need to test this scenario and confirm and fix.

**Comment by schamola** [comment]
pv_list is containing the list of PVs that need to be reduced. Both the messages are fine.

Example: 
command that is being run - reducing vg00 hdisk1 hdisk2

In case of success, the message would be - Physical volume(s) hdisk1 hdisk2 removed from Volume group vg00

And, in case of failure, the message would be - Failed to remove Physical volume(s) hdisk1 hdisk2 from Volume group vg00
