### ISSUE TITLE
Doc Clarification

### ISSUE THREAD

**Issue by s-man-g** [IBM/ansible-power-aix#49]
Hi Team,
Can we get a statement to clarify if AIX is supported as a control node?
Here:

https://github.com/IBM/ansible-power-aix/blob/dev-collection/docs/source/requirements.rst

**Comment by pbfinley1911** [comment]
There is a version of ansible which has been ported to AIX (and is available via AIX yum), but IBM doesn't provide service/support for the product, nor does Red Hat provide support.    Community-only

**Comment by kavanabhat** [comment]
@s-man-g, the official site for downloading AIX OpenSource packages is https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha
