### ISSUE TITLE
user module doesn't work if specifying a password in the module

### ISSUE THREAD

**Issue by Fchalon** [IBM/ansible-power-aix#521]
Hi,

I used ibm.power_aix collection to create user on AIX 7.2:
    
    - name: Create user (for AIX) 
       ibm.power_aix.user:
         state: "present"
         name: "{{ username }}"
         change_passwd_on_login: False
         attributes:
           home: "/home/{{ username }}"
           maxage: "30"
           pgrp: "{{ groupname }}"
      
   
    - name: Update user 
       ibm.power_aix.user:
         name: "{{ username }}"
         state: modify
         password: "{{ my_password | password_hash('sha512') }}"

User has been created on AIX server, but I can't connect with the new user using the password

 - OS:  AIX 7.2.0
 - Python 3.9.18
 - OpenSSH Version: [e.g. 1.0.2]
 - Ansible Version: 2.13.13
 - AIX Collection : ibm.power_aix     1.8.3

How to generate the encrypted password ?

**Comment by aklyachkin** [comment]
AFAIK today you can generate only MD5 passwords, see an example here - https://github.com/IBM/ansible-power-aix/issues/548

**Comment by schamola** [comment]
Hi @Fchalon 

For using "password_hash" filter to generate encrypted password, you need to download and install the following AIX web download pack : 
https://www.ibm.com/resources/mrs/assets?source=aixbp&S_PKG=pwmod

We have tested it on our environment and it seems to be working fine for us. You can see more information about it here - #548 

Can you please verify and let us know if It's working as expected in your Ansible setup ?

**Comment by nitismis** [comment]
We are tracking this issue through https://github.com/IBM/ansible-power-aix/issues/548 because it has more details. Marking this one as duplicate.
