### ISSUE TITLE
different versions in Ansible Galaxy and Github

### ISSUE THREAD

**Issue by ALutz273** [IBM/ansible-power-aix#527]
Hello everyone.

unfortunately there is a difference between the version in github.com page (version 1.8.1) 
and the Ansible Galaxy page (1.8.3) .

What has been changed in this version? 
Unfortunately, the changelog is also missing. 

![ansible-module-aix](https://github.com/IBM/ansible-power-aix/assets/72616997/14aabf7f-19d3-4203-8038-3650390b86bf)

**Comment by nitismis** [comment]
It has been updated to 1.9.2 in github, galaxy, and automation hub.
