### ISSUE TITLE
Chsec module not working for attributes having boolean values

### ISSUE THREAD

**Issue by schamola** [IBM/ansible-power-aix#529]
**Describe the bug**
Module exits in failure whenever an attribute having boolean value is being set or modified.

**To Reproduce**
Whenever I am trying to change/set the value of an attribute having boolean value, the module fails.

- name: Make the user admin
      ibm.power_aix.chsec:
        path: /etc/security/user
        stanza: testusr
        attrs:
          admin: true
        state: present

This is the error that I am receiving:

"msg": "Failed to run chsec command: /usr/bin/chsec -f /etc/security/user -s testusr -a admin=True",
    "rc": 1,
    "stderr": "3004-698 Error committing changes to \"testusr\".\n",

**Expected behavior**
Should change the attributes as mentioned and make the user admin.

**Comment by nitismis** [comment]
PR merged now.
