### ISSUE TITLE
user module to remove home directory too

### ISSUE THREAD

**Issue by cunlifs** [IBM/ansible-power-aix#56]
When using the ibm.power_aix.user module to remove a user, there is no option to also remove the users home directory. The ansible core user module does allow this via the remove/force options.

Would it be possible to allow your user module with state=absent to remove the home directory too.

**Comment by pbfinley1911** [comment]
Good idea @cunlifs 

We'll investigate very soon.

**Comment by pbfinley1911** [comment]
Available for download (all platforms)
