### ISSUE TITLE
Typo in nim_alt_disk_migration/tasks/add_alt_disk_install_fileset.yml

### ISSUE THREAD

**Issue by psmora** [IBM/ansible-power-aix#561]
Typo in nim_alt_disk_migration/tasks/add_alt_disk_install_fileset.yml

In line 10/11 the spot resource variable should be {{ nim_alt_disk_migration_spot }}  instead of  {{ spot }}

**To Reproduce**
IF a SPOT resource is specified AND the 'alt_disk_install' fileset is not installed in spot, when it tries to install that filesets it would error out saying spot not defined. 

**Expected behavior**
If the spot variable is correctly specified, it would proceed with installing the fileset. 

**Screenshots**

![image](https://github.com/user-attachments/assets/0ea7bb6a-5259-45a7-8b23-e9f38bb1ff67)

**Comment by nitismis** [comment]
Have merged the PR. Closing the issue.
