### ISSUE TITLE
Creating a new user with specific pgrp ID does not update the ownership of the home directory.

### ISSUE THREAD

**Issue by cunlifs** [IBM/ansible-power-aix#57]
When using ibm.power_aix.user state=present to build a new user along with the a pgrp attribute, the home directory appears to be created with another user id as owner.

1) Playbook/vars to recreate:
______________  
vars:
    user_name: ansible
    user_id: 999

    - name: Add user to AIX VM - skip if home directory exists or is wrong OS
      ibm.power_aix.user:
        state: present
        name: "{{ user_name }}"
        attributes:
          id: "{{ user_id }}"
________

2) Expected outcome:
To see the home directory owned by the user

3) Outcome:
Directory is owned by ID 211
[root@sc-tower-2 playbooks]# ssh root@lab-aix-1  ls -l /home                  
drwxr-xr-x    2 211      staff           256 Dec 08 09:50 ansible

We can see its owner is ID 211 - I think this was the next UID in sequence. So maybe the user ID gets created with with next ID in sequence (211) then changed to the required ID (999), however the home directory has already been created with ID 211

[root@sc-tower-2 playbooks]# ssh root@lab-aix-1  cat /etc/passwd | grep ansible
ansible:*:999:1::/home/ansible:/usr/bin/ksh

Shows that the userid is correct.

**Comment by pbfinley1911** [comment]
Thanks for opening.. we'll investigate for our next collection update (Dec 28th)

**Comment by kavanabhat** [comment]
Nitish,
 
Please handle this.
 
Regards,
Kavana
 
----- Original message -----From: PFin <notifications@github.com>To: IBM/ansible-power-aix <ansible-power-aix@noreply.github.com>Cc: kavanabhat <kavana.bhat@in.ibm.com>, Assign <assign@noreply.github.com>Subject: [EXTERNAL] Re: [IBM/ansible-power-aix] Creating a new user with specific pgrp ID does not update the ownership of the home directory. (#57)Date: Tue, Dec 8, 2020 9:47 PM 
 
Assigned #57 to @kavanabhat.

**Comment by pbfinley1911** [comment]
Available for download. (All platforms)
