### ISSUE TITLE
Please add "removed" as a device state 

### ISSUE THREAD

**Issue by AeXiPHiXiON** [IBM/ansible-power-aix#59]
Please add "removed" as a device state in devices.py to perform rmdev -dl <device>

  state:
    description:
    - Specifies the desired state of the device.
    - C(available) configures device when its state is 'defined', otherwise it changes the device
      attributes.
    - C(defined) unconfigures/stops the device when its state is 'available', otherwise it changes
      the device attributes.
    type: str
    choices: [ available, defined ]
    default: available

**Comment by pbfinley1911** [comment]
Thanks, we'll have a review (and response) shortly.
