### ISSUE TITLE
reboot – Reboot AIX machines

### ISSUE THREAD

**Issue by AeXiPHiXiON** [IBM/ansible-power-aix#60]
In the example, connect_timeout is invalid

    - name: "Reboot a machine"
      reboot:
        pre_reboot_delay: 20
        post_reboot_delay: 20
        connect_timeout: 10
        reboot_timeout: 300

**Comment by pbfinley1911** [comment]
Thanks.  We'll add back support for connect_timeout, but my understanding is that it doesn't work properly on AIX.. the team will review and plan accordingly.

**Comment by nitismis** [comment]
connect_timeout support was removed because it was increasing the turn around time for the task exponentially. That timeout period is handled with reboot_timeout and machine's connection default connect_timeout. So, removing connect_timeout parameter from the example as well.
