### ISSUE TITLE
alt_disk -> "No free disk available"

### ISSUE THREAD

**Issue by AeXiPHiXiON** [IBM/ansible-power-aix#61]
Fails with no disk available error, tried targets: hdisk1, disk_size_policy: nearest, and disk_size_policy: minimize. 

alt disk copy works fine from AIX cli

    TASK [Perform an alternate disk copy of the rootvg to hdisk1] fatal: [hostname]: FAILED! => {"changed": false, 
    "msg": "No free disk available", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

    - name: Perform an alternate disk copy of the rootvg to hdisk1
    ibm.power_aix.alt_disk:
      targets: hdisk1

This is the remote node info, same node used to test other modules successfully 

    root@:/root# lsdev -Cc disk
    hdisk0 Available 10-T1-01 MPIO FCP Default Disk
    hdisk1 Available 10-T1-01 MPIO FCP Default Disk

    root@:/root# lspv
    hdisk0          00fa4b4ada7835e9                    rootvg          active
    hdisk1          none                                None

    root@:/root# bootinfo -s hdisk1
    102400
    root@:/root# bootinfo -s hdisk0
    102400

**Comment by AeXiPHiXiON** [comment]
**commenting out the below lines in the get_free_pvs(module) fixed the issue**

    free_pvs = {}
    for line in stdout.split('\n'):
        line = line.rstrip()
        match_key = re.match(r"^(hdisk\S+)\s+(\S+)\s+(\S+)\s*(\S*)", line)
        # Only match disks that have no volume groups
        if match_key and match_key.group(3) == 'None':
            hdisk = match_key.group(1)
            # Check if the disk has an _LVM signature using lquerypv

 ### comment out the following
            cmd = ['lquerypv', '-V', hdisk]
            ret, stdout, stderr = module.run_command(cmd)
            if ret != 0:
                module.log('[WARN] could not query pv {0}'.format(hdisk))
                continue
            if stdout.strip() != "1":
                continue

**Comment by AeXiPHiXiON** [comment]
Looking into this further you're going to have issues with "lquerypv -V hdisk" unless you run "chpv -C hdisk" on all your unused disk prior to running the alt disk copy. Also many customers run some type of raw pv's like Oracle ASM which will show as a "free" hdisk with lquerypv -V

**Comment by AeXiPHiXiON** [comment]
probably better doing this, this still doesn't address the oracle asm issue

    #getlvodm -j hdisk4
    0516-320 getlvodm: Physical volume hdisk4 is not assigned to
        a volume group.
    #echo $?
    3

**Comment by pbfinley1911** [comment]
Ah, yes..  you're right!  I'll assign to the team for review.

Have you considered making contributions to our collection?  Pull requests are welcomed at this time and thanks again for the valuable insight.

**Comment by AeXiPHiXiON** [comment]
> 
> 
> Ah, yes.. you're right! I'll assign to the team for review.
> 
> Have you considered making contributions to our collection? Pull requests are welcomed at this time and thanks again for the valuable insight.

Let me get my python skills to the same level as my perl skills and yes I might be able to contribute ;)

**Comment by pvtorres** [comment]
Fix dropped and merged.
