### ISSUE TITLE
SMTCTL 

### ISSUE THREAD

**Issue by madhu-pillai** [IBM/ansible-power-aix#62]
Hi,
Good Day

I've written a Ansible module for smtctl (multithreading) for Power8 and Power9. I've tested and it is working fine.
Just wondering whether i can contribute to ibm.power_aix.

Please suggest.

Thanks
Madhu

**Comment by pbfinley1911** [comment]
Yes, please submit a PR and I'll review the content.  Thanks

https://github.com/IBM/ansible-power-aix/blob/dev-collection/CONTRIBUTING.md
