### ISSUE TITLE
Make emgr interim fix installation idempotent

### ISSUE THREAD

**Issue by woodstea23** [IBM/ansible-power-aix#69]
**Is your feature request related to a problem? Please describe.**
I tried installing an interim fix with the install action from the emgr module. It handled the installation of the new openssl_fix32 interim fix just fine, but if you run the playbook against the same host more than once, it errors.

**Describe the solution you'd like**
Ideally this should be idempotent -- you should be able to run this against the same host multiple times. Once the interim fix is installed, the install method should know that it is and not throw an error. Either you could do that by using a construction like "installed: true") similar to Ansible's built-in service module) rather than action: install, or just make sure the install action checks to see if an interim fix is installed before it tries to run "emgr -e <fix_file>".

**Describe alternatives you've considered**
As is -- without idempotence -- I'm not sure this has a lot of advantages over my usual NIM script strategy.

**Additional context**
I hope this doesn't come across to critical -- I'm definitely very happy to see this collection being developed!

**Comment by pbfinley1911** [comment]
Hi there! We have thick skin over here, so any constructive criticism is welcomed. 👍 

Let's see how soon it can be addressed.  Pull requests are acceptable as well ;)
