### ISSUE TITLE
Bootstrap playbook failing due to corrupted yum_bundle.tar file

### ISSUE THREAD

**Issue by Bhargava250** [IBM/ansible-power-aix#74]
**Describe the bug**
We are using this collection for installing yum and python on AIX managed server. 

**To Reproduce**
https://galaxy.ansible.com/ibm/power_aix
Downloaded tar file from ansible galaxy

Update ansible.cfg file and inventory file according to my env

After that the playbook execution is failing with below error

[root@p208n149 bootstrap]# ansible-playbook bootstrap.yml

PLAY [Bootstrap Yum on AIX] *******************************************************************************************************************************************

TASK [power_aix_bootstrap : Fail if pkgtype not specified] ************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if download_dir not specified] *******************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if target_dir not specified] *********************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if rpm_src not specified] ************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if yum_src not specified] ************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Bootstrap yum] ****************************************************************************************************************************
included: /root/bhar/bootstrap/power_aix/roles/power_aix_bootstrap/tasks/yum_install.yml for p227n243

TASK [power_aix_bootstrap : Check for existence of yum] ***************************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Check for rpm_src file on localhost] ******************************************************************************************************
ok: [p227n243]

TASK [power_aix_bootstrap : Download latest rpm (installp) fileset] ***************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Check for yum_src file on localhost] ******************************************************************************************************
ok: [p227n243]

TASK [power_aix_bootstrap : Download yum bundle file] *****************************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Check for script file on localhost] *******************************************************************************************************
ok: [p227n243]

TASK [power_aix_bootstrap : Copy the installer script file] ***********************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Check for target directory] ***************************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Check for target yum bundle] **************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Create target filesystem for image transfer] **********************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Mount target filesystem] ******************************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Transfer install images] ******************************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Restore yum bundle content] ***************************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Remove temporary storage space] ***********************************************************************************************************
changed: [p227n243]

TASK [power_aix_bootstrap : Print status] *****************************************************************************************************************************
ok: [p227n243] => {
    "msg": "Bootstrap attempt of yum on p227n243 has completed"
}

TASK [power_aix_bootstrap : Bootstrap python] *************************************************************************************************************************
skipping: [p227n243]

PLAY [Bootstrap Python on AIX] ****************************************************************************************************************************************

TASK [power_aix_bootstrap : Fail if pkgtype not specified] ************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if download_dir not specified] *******************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if target_dir not specified] *********************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if rpm_src not specified] ************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Fail if yum_src not specified] ************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Bootstrap yum] ****************************************************************************************************************************
skipping: [p227n243]

TASK [power_aix_bootstrap : Bootstrap python] *************************************************************************************************************************
fatal: [p227n243]: FAILED! => {"reason": "couldn't resolve module/action 'ibm.power_aix.filesystem'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/root/bhar/bootstrap/power_aix/roles/power_aix_bootstrap/tasks/python_install.yml': line 13, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# EXPAND target paths\n  - name: Expand /var target directory (+100M)\n    ^ here\n"}

PLAY RECAP ************************************************************************************************************************************************************
p227n243                   : ok=15   changed=10   unreachable=0    failed=1    skipped=13   rescued=0    ignored=0

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. AIX 7.2.4.0]
 - Python Version [e.g. 2.7.5, 3.6]
 - OpenSSH Version [e.g. 1.0.2]

**Additional context**

**Comment by Bhargava250** [comment]
After debugging identified that "yum_bundle.tar" file is getting downloaded from ftp server " ftp://ftp.software.ibm.com/aix/freeSoftware/aixtoolbox/ezinstall/ppc/yum_bundle.tar" and is getting corrupted and yum is not getting configured on AIX. 

# cksum yum_bundle.tar
1143754989 65371101 yum_bundle.tar <--- Wrong

# cksum yum_bundle.tar
744085116 54896640 yum_bundle.tar <--- Good


The collection should give a meaningful message when there is corruption of yum_bundle.tar file

**Comment by pvtorres** [comment]
Hi. I fixed a problem in the bootstrap module to install yum and python. 
There is a problem with the inventory_host flag and it will return errors during the process. 

https://github.com/IBM/ansible-power-aix/pull/168

Also looking deeper at the errors, I can see that the filesystem module can not be located. 

If you install the collections in a different path than the ansible_collections/ibm/power_aix, he call to the 
ibm.power_aix.filesystem will fail as it is trying to locate the filesystem module using that path. 

if you install the collections using the ansible-galaxy collection install ibm.power_aix, it will install the latest collection 
and it will install it in the location ( ~/.ansible/collections) that will work with the ibm.power_aix.filesystem, for example. 

You can also install the collections in another folder, but you will need to set the COLLECTIONS_PATHS=<path>/collections

**Comment by pvtorres** [comment]
I will close this case. Please re-open if you still find a problem with it.
