### ISSUE TITLE
Update ALL with local data

### ISSUE THREAD

**Issue by metabsd** [IBM/ansible-power-aix#77]
Hi,

Can I use this plugin to do the update but use already download bff ?
Thx!

https://github.com/IBM/ansible-power-aix/blob/3e0a50e377d5734addcf9e78a630a48beb1f0008/playbooks/demo_update-all-hosts.yml#L15

**Comment by pbfinley1911** [comment]
Hi,
The suma module will still attempt to discover updates, but will only download additional files if they aren't already present in the directory specified.  Afterwards, all files are used as part of an update_all routine.

If you're just wanting to run an install against a repository (without any additional checking upfront), then try using the geninstall module.
