### ISSUE TITLE
reboot module fails when specifying pre_reboot_delay in ad-hoc ansible command

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-power-aix#78]
When I run:

`ansible aix01 -m ibm.power_aix.reboot -a "pre_reboot_delay=20 post_reboot_delay=20 reboot_timeout=450 test_command=uname" -bK
`

I receive the following error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. **The error was: TypeError: an integer is required (got type str)**
aix01 | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""

```

If I run the command again but remove pre_reboot_delay I do not receive an error:

`ansible aix01 -m ibm.power_aix.reboot -a "post_reboot_delay=20 reboot_timeout=450 test_command=uname" -bK`

Is there anything specific I need to do to get pre_reboot_delay to work when using an ad-hoc ansible command?

**Comment by nitismis** [comment]
Hi Robin !
We are not able to recreate the issue with our test system or yml playbook files. Can you please copy the verbose output here. I mean output of the adhoc command with -vvv. I am able to run the playbook:
TASK [reboot the machine] ************************************************************************************************************************************************************************************************************************************
task path: /home/nitish/ansible-power-aix/reboot.yml:9
Waiting for pre reboot delay
System reboot process has started....
