### ISSUE TITLE
unable to perform vios health check

### ISSUE THREAD

**Issue by krishnahumagain** [IBM/ansible-power-aix#79]
**Describe the bug**
trying to execute vios health check playbook.  
---
- name: "VIOs health check playbook"
  hosts: nimna2
  gather_facts: no

  collections:
  - ibm.power_aix

  tasks:
    - name: Perform a health check
      nim_vios_hc:
        targets: "sharedna12vio1"
        action: health_check
      register: result
    - debug: var=result
#######Getting the following output, even though my VIOs is listed as nim object #########################
    output:
    - VIOS Health Check operation for ['sharedna12vio1']
    - '    Warning: Empty target list'
    status: {}
    stderr: ''
    stderr_lines: []
    stdout: ''
    stdout_lines: []
    targets: []

**Environment (please complete the following information):**
 - OS: [RHEL 7.7, Ansible 2.9]
 - Python Version [ 2.7.5]

**Comment by MGomathi** [comment]
This issue is fixed through #133 . This is available in the latest collection.
Please reopen the issue if you still face any errors.
