### ISSUE TITLE
Creating custom privileged group

### ISSUE THREAD

**Issue by JackHealyIBM** [IBM/ansible-power-aix#90]
**Describe the bug**
Not a bug, but I was asked to raise questions here

**To Reproduce**
I want to use ansible to run some custom automation on VIOS appliances.  The ansible user will need access to the /var/opt/ansible directory (and its subdirectories).

To achieve this, I believe that the ansible user will need to be in a new privileged group with rights to that directory.

Is this approach compliant with VIOS support?

If so, what commands should I user to create this ansible group, make it privileged and assign the ansible user to it?
If not, what compliant approach would achieve the same end result?

Thanks

**Comment by neikei** [comment]
Hi @JackHealyIBM, the most common solution is an entry in /etc/sudoers for your Ansible user and the "become"-switch in your playbook. So that the Ansible user has full access to all ressources of the VIO. I am not sure if this is compatible with your authorisation concept and I don't know why you need access to the path /var/opt/ansible, but I will share a short example with you. The Ansible user can use /usr/ios/cli/ioscli to execute specific VIO commands if needed.

_/etc/sudoers example_

```bash
# grep ansibleuser /etc/sudoers
ansibleuser ALL=(ALL) NOPASSWD: ALL
```

_Playbook example_

```bash
- name: "Playbook for VIOs"
  hosts: vios
  become: yes
  tasks:
     ....
```

_Is this approach compliant with VIOS support?_ -> Please open a Case at https://www.ibm.com/mysupport to get an official answer for this question.

**Comment by DerringDo** [comment]
Thanks neikei for replying

I'm not certain that this approach will work, as the playbooks which are common across a range of OS'es expect not to have to become system to manage files in that directory.   I was hoping to avoid changing the logic just for VIOS.

**Comment by neikei** [comment]
Okay, I got it and checked one of our VIOs, but I don't see a solution for it with the default permissions and without system as group. We've been using ansible for a while now and I can't find a /var/opt/ansible folder on any of our systems. Can you share which playbook you are using?

_Default permissions for /var/opt_

```bash
# ls -ld /var/opt
drwxr-xr-x    6 root     system            256 Apr 09 13:01 /var/opt
```

**Comment by JackHealyIBM** [comment]
The playbooks are not part of any standard suite, but are custom playbooks used to manage multiple flavors of unix-like operating systems.  Across all of these OS'es, we are able to maintain configuration files etc in /var/opt/ansible, and would like to do the same on VIOS, rather than having to have VIOS-specific versions of these playbooks.  Thanks

**Comment by MGomathi** [comment]
We can try to create a ansible user with all privileged access as part of role and assign to it. This should give access to those folders for which root is the owner.

If we are looking for that , below is the  the command to add the privilege roles to the ansible user that we want to create from padmin restricted shell in VIOS:

 mkuser -attr "default_roles=PAdmin,CacheAdm,FSAdmin,pkgadm"  "roles=PAdmin,CacheAdm,FSAdmin,pkgadm" ansible

**Comment by MGomathi** [comment]
We can try to create a ansible user with all Admin access privilege as part of role and assign to it.  This should give access to those folders for which root is the owner.
Are you looking for that ?

Following is the command to add privileged administrative rights to the ansible user that we want to create from oem_setup_env prompt .

Example:  To add only FS related privileges you can run like below
 oem_setup_env
 
 mkuser roles=FSAdmin default_roles=FSAdmin testuser

 Similarly you can add the roles to the user with “chuser” command in oem_setup_env depending on the requirement.

“lsrole ALL” command will give the details of the roles and their authorizations.

**Comment by pvtorres** [comment]
Please let us know if @MGomathi suggestion works for you.
