### ISSUE TITLE
Add more options to alt-disk: -P, -b, -l, -I (create a copy, remove efixes, update_all)

### ISSUE THREAD

**Issue by 0rphu** [IBM/ansible-power-aix#93]
When performing an OS update, I always use alt_disk_copy -P1 to create a copy, then remove the efixes from alt_disk with chroot, and afterwards use -P23 with -b update_all to update the alt disk.

I'd like the alt_disk module to support the following flags: -P, -b, -l, -I

**Comment by nitismis** [comment]
We have planned this in our next release. Will track this item through a new issue.
